/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinova_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {22, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* kinova_cost_ext_cost_e_fun_jac:(i0[15],i1[],i2[],i3[22])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+10, w03, w04, *w05=w+20, *w06=w+23, w08, w09, w10, w11;
  casadi_real *w12=w+57, w13, w14, *w15=w+63, *w16=w+67, *w17=w+71, *w18=w+75, *w19=w+91, *w20=w+107, *w21=w+139, *w22=w+171, *w23=w+187;
  casadi_real *w24=w+219, *w25=w+283, w26, w27, w28, w29, w30, w31, w32, w33, w34, *w35=w+356;
  casadi_real *w36=w+371, *w37=w+379, w38, w39, w40, w41, *w42=w+386, w43, *w44=w+391, *w45=w+399, *w46=w+407;
  const casadi_real *cs, *ct, *wr07;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w02, 8);
  /* #3: @3 = 0 */
  w03 = 0.;
  /* #4: @4 = 0.5 */
  w04 = 5.0000000000000000e-01;
  /* #5: @5 = all_2.22045e-16(3x1) */
  casadi_fill(w05, 3, 2.2204460492503131e-16);
  /* #6: @6 = zeros(8x1) */
  casadi_clear(w06, 8);
  /* #7: @7 = input[3][0] */
  wr07 = arg[3] ? arg[3] : casadi_zeros;
  /* #8: @8 = @7[0] */
  w08 = wr07[0];
  /* #9: @9 = @7[1] */
  w09 = wr07[1];
  /* #10: @10 = @7[2] */
  w10 = wr07[2];
  /* #11: @11 = @7[3] */
  w11 = wr07[3];
  /* #12: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #13: @12 = @12' */
  /* #14: @8 = (-@9) */
  w08 = (- w09 );
  /* #15: @13 = @7[0] */
  w13 = wr07[0];
  /* #16: @14 = (-@10) */
  w14 = (- w10 );
  /* #17: @15 = horzcat(@8, @13, @11, @14) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w14;
  /* #18: @15 = @15' */
  /* #19: @11 = (-@11) */
  w11 = (- w11 );
  /* #20: @13 = @7[0] */
  w13 = wr07[0];
  /* #21: @16 = horzcat(@14, @11, @13, @9) */
  rr=w16;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w09;
  /* #22: @16 = @16' */
  /* #23: @14 = @7[0] */
  w14 = wr07[0];
  /* #24: @17 = horzcat(@11, @10, @8, @14) */
  rr=w17;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  /* #25: @17 = @17' */
  /* #26: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #27: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #28: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #29: @20 = horzcat(@19, @18) */
  rr=w20;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #30: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #31: @11 = @7[4] */
  w11 = wr07[4];
  /* #32: @10 = @7[5] */
  w10 = wr07[5];
  /* #33: @8 = @7[6] */
  w08 = wr07[6];
  /* #34: @14 = @7[7] */
  w14 = wr07[7];
  /* #35: @12 = horzcat(@11, @10, @8, @14) */
  rr=w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  /* #36: @12 = @12' */
  /* #37: @11 = (-@10) */
  w11 = (- w10 );
  /* #38: @13 = @7[4] */
  w13 = wr07[4];
  /* #39: @9 = (-@8) */
  w09 = (- w08 );
  /* #40: @15 = horzcat(@11, @13, @14, @9) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w09;
  /* #41: @15 = @15' */
  /* #42: @14 = (-@14) */
  w14 = (- w14 );
  /* #43: @13 = @7[4] */
  w13 = wr07[4];
  /* #44: @16 = horzcat(@9, @14, @13, @10) */
  rr=w16;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w10;
  /* #45: @16 = @16' */
  /* #46: @9 = @7[4] */
  w09 = wr07[4];
  /* #47: @17 = horzcat(@14, @8, @11, @9) */
  rr=w17;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w09;
  /* #48: @17 = @17' */
  /* #49: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #50: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #51: @20 = horzcat(@22, @19) */
  rr=w20;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  /* #52: @23 = @20' */
  for (i=0, rr=w23, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #53: @24 = horzcat(@21, @23) */
  rr=w24;
  for (i=0, cs=w21; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<32; ++i) *rr++ = *cs++;
  /* #54: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #55: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #56: @8 = input[0][1] */
  w08 = arg[0] ? arg[0][1] : 0;
  /* #57: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #58: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #59: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #60: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #61: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #62: @27 = input[0][7] */
  w27 = arg[0] ? arg[0][7] : 0;
  /* #63: @28 = input[0][8] */
  w28 = arg[0] ? arg[0][8] : 0;
  /* #64: @29 = input[0][9] */
  w29 = arg[0] ? arg[0][9] : 0;
  /* #65: @30 = input[0][10] */
  w30 = arg[0] ? arg[0][10] : 0;
  /* #66: @31 = input[0][11] */
  w31 = arg[0] ? arg[0][11] : 0;
  /* #67: @32 = input[0][12] */
  w32 = arg[0] ? arg[0][12] : 0;
  /* #68: @33 = input[0][13] */
  w33 = arg[0] ? arg[0][13] : 0;
  /* #69: @34 = input[0][14] */
  w34 = arg[0] ? arg[0][14] : 0;
  /* #70: @35 = vertcat(@14, @8, @11, @9, @13, @10, @26, @27, @28, @29, @30, @31, @32, @33, @34) */
  rr=w35;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  /* #71: @36 = @35[:8] */
  for (rr=w36, cs=w35+0; cs!=w35+8; cs+=1) *rr++ = *cs;
  /* #72: @6 = mac(@25,@36,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w25+j, ct=w36+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #73: @37 = @6[1:4] */
  for (rr=w37, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #74: @5 = (@5+@37) */
  for (i=0, rr=w05, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #75: @14 = ||@5||_F */
  w14 = casadi_norm_2(3, w05);
  /* #76: @8 = @6[0] */
  for (rr=(&w08), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #77: @11 = atan2(@14,@8) */
  w11  = atan2(w14,w08);
  /* #78: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #79: @9 = (@4*@11) */
  w09  = (w04*w11);
  /* #80: @13 = @6[1] */
  for (rr=(&w13), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #81: @10 = (@9*@13) */
  w10  = (w09*w13);
  /* #82: @10 = (@10/@14) */
  w10 /= w14;
  /* #83: @26 = 0.5 */
  w26 = 5.0000000000000000e-01;
  /* #84: @27 = (@26*@11) */
  w27  = (w26*w11);
  /* #85: @28 = @6[2] */
  for (rr=(&w28), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #86: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #87: @29 = (@29/@14) */
  w29 /= w14;
  /* #88: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #89: @11 = (@30*@11) */
  w11  = (w30*w11);
  /* #90: @31 = @6[3] */
  for (rr=(&w31), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #91: @32 = (@11*@31) */
  w32  = (w11*w31);
  /* #92: @32 = (@32/@14) */
  w32 /= w14;
  /* #93: @33 = 0 */
  w33 = 0.;
  /* #94: @34 = 0.5 */
  w34 = 5.0000000000000000e-01;
  /* #95: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #96: @38 = @6[4] */
  for (rr=(&w38), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #97: @39 = @6[5] */
  for (rr=(&w39), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #98: @39 = (-@39) */
  w39 = (- w39 );
  /* #99: @40 = @6[6] */
  for (rr=(&w40), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #100: @40 = (-@40) */
  w40 = (- w40 );
  /* #101: @41 = @6[7] */
  for (rr=(&w41), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #102: @41 = (-@41) */
  w41 = (- w41 );
  /* #103: @15 = horzcat(@38, @39, @40, @41) */
  rr=w15;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #104: @15 = @15' */
  /* #105: @38 = @6[5] */
  for (rr=(&w38), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #106: @39 = @6[4] */
  for (rr=(&w39), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #107: @40 = @6[7] */
  for (rr=(&w40), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #108: @40 = (-@40) */
  w40 = (- w40 );
  /* #109: @41 = @6[6] */
  for (rr=(&w41), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #110: @16 = horzcat(@38, @39, @40, @41) */
  rr=w16;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #111: @16 = @16' */
  /* #112: @38 = @6[6] */
  for (rr=(&w38), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #113: @39 = @6[7] */
  for (rr=(&w39), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #114: @40 = @6[4] */
  for (rr=(&w40), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #115: @41 = @6[5] */
  for (rr=(&w41), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #116: @41 = (-@41) */
  w41 = (- w41 );
  /* #117: @17 = horzcat(@38, @39, @40, @41) */
  rr=w17;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #118: @17 = @17' */
  /* #119: @38 = @6[7] */
  for (rr=(&w38), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #120: @39 = @6[6] */
  for (rr=(&w39), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #121: @39 = (-@39) */
  w39 = (- w39 );
  /* #122: @40 = @6[5] */
  for (rr=(&w40), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #123: @41 = @6[4] */
  for (rr=(&w41), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #124: @42 = horzcat(@38, @39, @40, @41) */
  rr=w42;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #125: @42 = @42' */
  /* #126: @22 = horzcat(@15, @16, @17, @42) */
  rr=w22;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<4; ++i) *rr++ = *cs++;
  /* #127: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #128: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #129: @38 = @6[0] */
  for (rr=(&w38), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #130: @39 = @6[1] */
  for (rr=(&w39), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #131: @39 = (-@39) */
  w39 = (- w39 );
  /* #132: @40 = @6[2] */
  for (rr=(&w40), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #133: @40 = (-@40) */
  w40 = (- w40 );
  /* #134: @41 = @6[3] */
  for (rr=(&w41), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #135: @41 = (-@41) */
  w41 = (- w41 );
  /* #136: @15 = vertcat(@38, @39, @40, @41) */
  rr=w15;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #137: @12 = mac(@19,@15,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w19+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #138: @38 = @12[1] */
  for (rr=(&w38), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #139: @38 = (@34*@38) */
  w38  = (w34*w38);
  /* #140: @39 = 0.5 */
  w39 = 5.0000000000000000e-01;
  /* #141: @40 = @12[2] */
  for (rr=(&w40), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #142: @40 = (@39*@40) */
  w40  = (w39*w40);
  /* #143: @41 = 0.5 */
  w41 = 5.0000000000000000e-01;
  /* #144: @43 = @12[3] */
  for (rr=(&w43), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #145: @43 = (@41*@43) */
  w43  = (w41*w43);
  /* #146: @6 = vertcat(@3, @10, @29, @32, @33, @38, @40, @43) */
  rr=w06;
  *rr++ = w03;
  *rr++ = w10;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w43;
  /* #147: @36 = @6' */
  casadi_copy(w06, 8, w36);
  /* #148: @25 = zeros(8x8) */
  casadi_clear(w25, 64);
  /* #149: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #150: (@25[0] = @3) */
  for (rr=w25+0, cs=(&w03); rr!=w25+1; rr+=1) *rr = *cs++;
  /* #151: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #152: (@25[9] = @3) */
  for (rr=w25+9, cs=(&w03); rr!=w25+10; rr+=1) *rr = *cs++;
  /* #153: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #154: (@25[18] = @3) */
  for (rr=w25+18, cs=(&w03); rr!=w25+19; rr+=1) *rr = *cs++;
  /* #155: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #156: (@25[27] = @3) */
  for (rr=w25+27, cs=(&w03); rr!=w25+28; rr+=1) *rr = *cs++;
  /* #157: @3 = 2 */
  w03 = 2.;
  /* #158: (@25[36] = @3) */
  for (rr=w25+36, cs=(&w03); rr!=w25+37; rr+=1) *rr = *cs++;
  /* #159: @3 = 2 */
  w03 = 2.;
  /* #160: (@25[45] = @3) */
  for (rr=w25+45, cs=(&w03); rr!=w25+46; rr+=1) *rr = *cs++;
  /* #161: @3 = 2 */
  w03 = 2.;
  /* #162: (@25[54] = @3) */
  for (rr=w25+54, cs=(&w03); rr!=w25+55; rr+=1) *rr = *cs++;
  /* #163: @3 = 2 */
  w03 = 2.;
  /* #164: (@25[63] = @3) */
  for (rr=w25+63, cs=(&w03); rr!=w25+64; rr+=1) *rr = *cs++;
  /* #165: @2 = mac(@36,@25,@2) */
  for (i=0, rr=w02; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w25+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @1 = mac(@2,@6,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=w06+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #167: @0 = (@0*@1) */
  w00 *= w01;
  /* #168: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #169: @35 = zeros(15x1) */
  casadi_clear(w35, 15);
  /* #170: @36 = zeros(8x1) */
  casadi_clear(w36, 8);
  /* #171: @44 = zeros(8x1) */
  casadi_clear(w44, 8);
  /* #172: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #173: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #174: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #175: @0 = 10 */
  w00 = 10.;
  /* #176: @2 = @2' */
  /* #177: @2 = (@0*@2) */
  for (i=0, rr=w02, cs=w02; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #178: @45 = zeros(1x8) */
  casadi_clear(w45, 8);
  /* #179: @6 = @6' */
  /* #180: @6 = (@0*@6) */
  for (i=0, rr=w06, cs=w06; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #181: @46 = @25' */
  for (i=0, rr=w46, cs=w25; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #182: @45 = mac(@6,@46,@45) */
  for (i=0, rr=w45; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w46+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #183: @45 = @45' */
  /* #184: @2 = (@2+@45) */
  for (i=0, rr=w02, cs=w45; i<8; ++i) (*rr++) += (*cs++);
  /* #185: {NULL, @0, @1, @3, NULL, @33, @38, @40} = vertsplit(@2) */
  w00 = w02[1];
  w01 = w02[2];
  w03 = w02[3];
  w33 = w02[5];
  w38 = w02[6];
  w40 = w02[7];
  /* #186: @41 = (@41*@40) */
  w41 *= w40;
  /* #187: (@16[3] += @41) */
  for (rr=w16+3, cs=(&w41); rr!=w16+4; rr+=1) *rr += *cs++;
  /* #188: @39 = (@39*@38) */
  w39 *= w38;
  /* #189: (@16[2] += @39) */
  for (rr=w16+2, cs=(&w39); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #190: @34 = (@34*@33) */
  w34 *= w33;
  /* #191: (@16[1] += @34) */
  for (rr=w16+1, cs=(&w34); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #192: @12 = mac(@22,@16,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w22+j, ct=w16+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #193: {@34, @33, @39, @38} = vertsplit(@12) */
  w34 = w12[0];
  w33 = w12[1];
  w39 = w12[2];
  w38 = w12[3];
  /* #194: @38 = (-@38) */
  w38 = (- w38 );
  /* #195: (@44[3] += @38) */
  for (rr=w44+3, cs=(&w38); rr!=w44+4; rr+=1) *rr += *cs++;
  /* #196: @39 = (-@39) */
  w39 = (- w39 );
  /* #197: (@44[2] += @39) */
  for (rr=w44+2, cs=(&w39); rr!=w44+3; rr+=1) *rr += *cs++;
  /* #198: @33 = (-@33) */
  w33 = (- w33 );
  /* #199: (@44[1] += @33) */
  for (rr=w44+1, cs=(&w33); rr!=w44+2; rr+=1) *rr += *cs++;
  /* #200: (@44[0] += @34) */
  for (rr=w44+0, cs=(&w34); rr!=w44+1; rr+=1) *rr += *cs++;
  /* #201: @22 = zeros(4x4) */
  casadi_clear(w22, 16);
  /* #202: @15 = @15' */
  /* #203: @22 = mac(@16,@15,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w16+j, ct=w15+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #204: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #205: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #206: {@16, @15, @12, @17} = horzsplit(@19) */
  casadi_copy(w19, 4, w16);
  casadi_copy(w19+4, 4, w15);
  casadi_copy(w19+8, 4, w12);
  casadi_copy(w19+12, 4, w17);
  /* #207: @17 = @17' */
  /* #208: {@34, @33, @39, @38} = horzsplit(@17) */
  w34 = w17[0];
  w33 = w17[1];
  w39 = w17[2];
  w38 = w17[3];
  /* #209: (@44[4] += @38) */
  for (rr=w44+4, cs=(&w38); rr!=w44+5; rr+=1) *rr += *cs++;
  /* #210: (@44[5] += @39) */
  for (rr=w44+5, cs=(&w39); rr!=w44+6; rr+=1) *rr += *cs++;
  /* #211: @33 = (-@33) */
  w33 = (- w33 );
  /* #212: (@44[6] += @33) */
  for (rr=w44+6, cs=(&w33); rr!=w44+7; rr+=1) *rr += *cs++;
  /* #213: (@44[7] += @34) */
  for (rr=w44+7, cs=(&w34); rr!=w44+8; rr+=1) *rr += *cs++;
  /* #214: @12 = @12' */
  /* #215: {@34, @33, @39, @38} = horzsplit(@12) */
  w34 = w12[0];
  w33 = w12[1];
  w39 = w12[2];
  w38 = w12[3];
  /* #216: @38 = (-@38) */
  w38 = (- w38 );
  /* #217: (@44[5] += @38) */
  for (rr=w44+5, cs=(&w38); rr!=w44+6; rr+=1) *rr += *cs++;
  /* #218: (@44[4] += @39) */
  for (rr=w44+4, cs=(&w39); rr!=w44+5; rr+=1) *rr += *cs++;
  /* #219: (@44[7] += @33) */
  for (rr=w44+7, cs=(&w33); rr!=w44+8; rr+=1) *rr += *cs++;
  /* #220: (@44[6] += @34) */
  for (rr=w44+6, cs=(&w34); rr!=w44+7; rr+=1) *rr += *cs++;
  /* #221: @15 = @15' */
  /* #222: {@34, @33, @39, @38} = horzsplit(@15) */
  w34 = w15[0];
  w33 = w15[1];
  w39 = w15[2];
  w38 = w15[3];
  /* #223: (@44[6] += @38) */
  for (rr=w44+6, cs=(&w38); rr!=w44+7; rr+=1) *rr += *cs++;
  /* #224: @39 = (-@39) */
  w39 = (- w39 );
  /* #225: (@44[7] += @39) */
  for (rr=w44+7, cs=(&w39); rr!=w44+8; rr+=1) *rr += *cs++;
  /* #226: (@44[4] += @33) */
  for (rr=w44+4, cs=(&w33); rr!=w44+5; rr+=1) *rr += *cs++;
  /* #227: (@44[5] += @34) */
  for (rr=w44+5, cs=(&w34); rr!=w44+6; rr+=1) *rr += *cs++;
  /* #228: @16 = @16' */
  /* #229: {@34, @33, @39, @38} = horzsplit(@16) */
  w34 = w16[0];
  w33 = w16[1];
  w39 = w16[2];
  w38 = w16[3];
  /* #230: @38 = (-@38) */
  w38 = (- w38 );
  /* #231: (@44[7] += @38) */
  for (rr=w44+7, cs=(&w38); rr!=w44+8; rr+=1) *rr += *cs++;
  /* #232: @39 = (-@39) */
  w39 = (- w39 );
  /* #233: (@44[6] += @39) */
  for (rr=w44+6, cs=(&w39); rr!=w44+7; rr+=1) *rr += *cs++;
  /* #234: @33 = (-@33) */
  w33 = (- w33 );
  /* #235: (@44[5] += @33) */
  for (rr=w44+5, cs=(&w33); rr!=w44+6; rr+=1) *rr += *cs++;
  /* #236: (@44[4] += @34) */
  for (rr=w44+4, cs=(&w34); rr!=w44+5; rr+=1) *rr += *cs++;
  /* #237: @34 = (@3/@14) */
  w34  = (w03/w14);
  /* #238: @11 = (@11*@34) */
  w11 *= w34;
  /* #239: (@44[3] += @11) */
  for (rr=w44+3, cs=(&w11); rr!=w44+4; rr+=1) *rr += *cs++;
  /* #240: @11 = (@1/@14) */
  w11  = (w01/w14);
  /* #241: @27 = (@27*@11) */
  w27 *= w11;
  /* #242: (@44[2] += @27) */
  for (rr=w44+2, cs=(&w27); rr!=w44+3; rr+=1) *rr += *cs++;
  /* #243: @27 = (@0/@14) */
  w27  = (w00/w14);
  /* #244: @9 = (@9*@27) */
  w09 *= w27;
  /* #245: (@44[1] += @9) */
  for (rr=w44+1, cs=(&w09); rr!=w44+2; rr+=1) *rr += *cs++;
  /* #246: @9 = sq(@14) */
  w09 = casadi_sq( w14 );
  /* #247: @33 = sq(@8) */
  w33 = casadi_sq( w08 );
  /* #248: @9 = (@9+@33) */
  w09 += w33;
  /* #249: @33 = (@14/@9) */
  w33  = (w14/w09);
  /* #250: @31 = (@31*@34) */
  w31 *= w34;
  /* #251: @30 = (@30*@31) */
  w30 *= w31;
  /* #252: @28 = (@28*@11) */
  w28 *= w11;
  /* #253: @26 = (@26*@28) */
  w26 *= w28;
  /* #254: @30 = (@30+@26) */
  w30 += w26;
  /* #255: @13 = (@13*@27) */
  w13 *= w27;
  /* #256: @4 = (@4*@13) */
  w04 *= w13;
  /* #257: @30 = (@30+@4) */
  w30 += w04;
  /* #258: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #259: @33 = (@33*@30) */
  w33 *= w30;
  /* #260: @33 = (-@33) */
  w33 = (- w33 );
  /* #261: (@44[0] += @33) */
  for (rr=w44+0, cs=(&w33); rr!=w44+1; rr+=1) *rr += *cs++;
  /* #262: @29 = (@29/@14) */
  w29 /= w14;
  /* #263: @29 = (@29*@1) */
  w29 *= w01;
  /* #264: @29 = (-@29) */
  w29 = (- w29 );
  /* #265: @32 = (@32/@14) */
  w32 /= w14;
  /* #266: @32 = (@32*@3) */
  w32 *= w03;
  /* #267: @29 = (@29-@32) */
  w29 -= w32;
  /* #268: @10 = (@10/@14) */
  w10 /= w14;
  /* #269: @10 = (@10*@0) */
  w10 *= w00;
  /* #270: @29 = (@29-@10) */
  w29 -= w10;
  /* #271: @8 = (@8/@9) */
  w08 /= w09;
  /* #272: @8 = (@8*@30) */
  w08 *= w30;
  /* #273: @29 = (@29+@8) */
  w29 += w08;
  /* #274: @29 = (@29/@14) */
  w29 /= w14;
  /* #275: @5 = (@29*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #276: (@44[1:4] += @5) */
  for (rr=w44+1, cs=w05; rr!=w44+4; rr+=1) *rr += *cs++;
  /* #277: @36 = mac(@24,@44,@36) */
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w44+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #278: (@35[:8] += @36) */
  for (rr=w35+0, cs=w36; rr!=w35+8; rr+=1) *rr += *cs++;
  /* #279: output[1][0] = @35 */
  casadi_copy(w35, 15, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real kinova_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 471;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 471*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
