/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinova_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* kinova_cost_ext_cost_fun:(i0[15],i1[7],i2[],i3[22])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+10, w03, w04, *w05=w+20, *w06=w+23, w08, w09, w10, w11;
  casadi_real *w12=w+57, w13, w14, *w15=w+63, *w16=w+67, *w17=w+71, *w18=w+75, *w19=w+91, *w20=w+107, *w21=w+139, *w22=w+171, *w23=w+187;
  casadi_real *w24=w+219, *w25=w+283, w26, w27, w28, w29, w30, w31, w32, w33, w34, *w35=w+356;
  casadi_real *w36=w+371, *w37=w+379, *w38=w+382, *w39=w+386, *w40=w+393, *w41=w+400, *w42=w+407;
  const casadi_real *cr, *cs, *ct, *wr07, *wr40;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w02, 8);
  /* #3: @3 = 0 */
  w03 = 0.;
  /* #4: @4 = 0.5 */
  w04 = 5.0000000000000000e-01;
  /* #5: @5 = all_2.22045e-16(3x1) */
  casadi_fill(w05, 3, 2.2204460492503131e-16);
  /* #6: @6 = zeros(8x1) */
  casadi_clear(w06, 8);
  /* #7: @7 = input[3][0] */
  wr07 = arg[3] ? arg[3] : casadi_zeros;
  /* #8: @8 = @7[0] */
  w08 = wr07[0];
  /* #9: @9 = @7[1] */
  w09 = wr07[1];
  /* #10: @10 = @7[2] */
  w10 = wr07[2];
  /* #11: @11 = @7[3] */
  w11 = wr07[3];
  /* #12: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #13: @12 = @12' */
  /* #14: @8 = (-@9) */
  w08 = (- w09 );
  /* #15: @13 = @7[0] */
  w13 = wr07[0];
  /* #16: @14 = (-@10) */
  w14 = (- w10 );
  /* #17: @15 = horzcat(@8, @13, @11, @14) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w14;
  /* #18: @15 = @15' */
  /* #19: @11 = (-@11) */
  w11 = (- w11 );
  /* #20: @13 = @7[0] */
  w13 = wr07[0];
  /* #21: @16 = horzcat(@14, @11, @13, @9) */
  rr=w16;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w09;
  /* #22: @16 = @16' */
  /* #23: @14 = @7[0] */
  w14 = wr07[0];
  /* #24: @17 = horzcat(@11, @10, @8, @14) */
  rr=w17;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  /* #25: @17 = @17' */
  /* #26: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #27: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #28: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #29: @20 = horzcat(@19, @18) */
  rr=w20;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #30: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #31: @11 = @7[4] */
  w11 = wr07[4];
  /* #32: @10 = @7[5] */
  w10 = wr07[5];
  /* #33: @8 = @7[6] */
  w08 = wr07[6];
  /* #34: @14 = @7[7] */
  w14 = wr07[7];
  /* #35: @12 = horzcat(@11, @10, @8, @14) */
  rr=w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  /* #36: @12 = @12' */
  /* #37: @11 = (-@10) */
  w11 = (- w10 );
  /* #38: @13 = @7[4] */
  w13 = wr07[4];
  /* #39: @9 = (-@8) */
  w09 = (- w08 );
  /* #40: @15 = horzcat(@11, @13, @14, @9) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w09;
  /* #41: @15 = @15' */
  /* #42: @14 = (-@14) */
  w14 = (- w14 );
  /* #43: @13 = @7[4] */
  w13 = wr07[4];
  /* #44: @16 = horzcat(@9, @14, @13, @10) */
  rr=w16;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w10;
  /* #45: @16 = @16' */
  /* #46: @9 = @7[4] */
  w09 = wr07[4];
  /* #47: @17 = horzcat(@14, @8, @11, @9) */
  rr=w17;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w09;
  /* #48: @17 = @17' */
  /* #49: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #50: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #51: @20 = horzcat(@22, @19) */
  rr=w20;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  /* #52: @23 = @20' */
  for (i=0, rr=w23, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #53: @24 = horzcat(@21, @23) */
  rr=w24;
  for (i=0, cs=w21; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<32; ++i) *rr++ = *cs++;
  /* #54: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #55: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #56: @8 = input[0][1] */
  w08 = arg[0] ? arg[0][1] : 0;
  /* #57: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #58: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #59: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #60: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #61: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #62: @27 = input[0][7] */
  w27 = arg[0] ? arg[0][7] : 0;
  /* #63: @28 = input[0][8] */
  w28 = arg[0] ? arg[0][8] : 0;
  /* #64: @29 = input[0][9] */
  w29 = arg[0] ? arg[0][9] : 0;
  /* #65: @30 = input[0][10] */
  w30 = arg[0] ? arg[0][10] : 0;
  /* #66: @31 = input[0][11] */
  w31 = arg[0] ? arg[0][11] : 0;
  /* #67: @32 = input[0][12] */
  w32 = arg[0] ? arg[0][12] : 0;
  /* #68: @33 = input[0][13] */
  w33 = arg[0] ? arg[0][13] : 0;
  /* #69: @34 = input[0][14] */
  w34 = arg[0] ? arg[0][14] : 0;
  /* #70: @35 = vertcat(@14, @8, @11, @9, @13, @10, @26, @27, @28, @29, @30, @31, @32, @33, @34) */
  rr=w35;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  /* #71: @36 = @35[:8] */
  for (rr=w36, cs=w35+0; cs!=w35+8; cs+=1) *rr++ = *cs;
  /* #72: @6 = mac(@25,@36,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w25+j, ct=w36+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #73: @37 = @6[1:4] */
  for (rr=w37, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #74: @5 = (@5+@37) */
  for (i=0, rr=w05, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #75: @14 = ||@5||_F */
  w14 = casadi_norm_2(3, w05);
  /* #76: @8 = @6[0] */
  for (rr=(&w08), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #77: @8 = atan2(@14,@8) */
  w08  = atan2(w14,w08);
  /* #78: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #79: @4 = (@4*@8) */
  w04 *= w08;
  /* #80: @11 = @6[1] */
  for (rr=(&w11), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #81: @4 = (@4*@11) */
  w04 *= w11;
  /* #82: @4 = (@4/@14) */
  w04 /= w14;
  /* #83: @11 = 0.5 */
  w11 = 5.0000000000000000e-01;
  /* #84: @11 = (@11*@8) */
  w11 *= w08;
  /* #85: @9 = @6[2] */
  for (rr=(&w09), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #86: @11 = (@11*@9) */
  w11 *= w09;
  /* #87: @11 = (@11/@14) */
  w11 /= w14;
  /* #88: @9 = 0.5 */
  w09 = 5.0000000000000000e-01;
  /* #89: @9 = (@9*@8) */
  w09 *= w08;
  /* #90: @8 = @6[3] */
  for (rr=(&w08), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #91: @9 = (@9*@8) */
  w09 *= w08;
  /* #92: @9 = (@9/@14) */
  w09 /= w14;
  /* #93: @14 = 0 */
  w14 = 0.;
  /* #94: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #95: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #96: @13 = @6[4] */
  for (rr=(&w13), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #97: @10 = @6[5] */
  for (rr=(&w10), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #98: @10 = (-@10) */
  w10 = (- w10 );
  /* #99: @26 = @6[6] */
  for (rr=(&w26), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #100: @26 = (-@26) */
  w26 = (- w26 );
  /* #101: @27 = @6[7] */
  for (rr=(&w27), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #102: @27 = (-@27) */
  w27 = (- w27 );
  /* #103: @15 = horzcat(@13, @10, @26, @27) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  /* #104: @15 = @15' */
  /* #105: @13 = @6[5] */
  for (rr=(&w13), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #106: @10 = @6[4] */
  for (rr=(&w10), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #107: @26 = @6[7] */
  for (rr=(&w26), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #108: @26 = (-@26) */
  w26 = (- w26 );
  /* #109: @27 = @6[6] */
  for (rr=(&w27), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #110: @16 = horzcat(@13, @10, @26, @27) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  /* #111: @16 = @16' */
  /* #112: @13 = @6[6] */
  for (rr=(&w13), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #113: @10 = @6[7] */
  for (rr=(&w10), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #114: @26 = @6[4] */
  for (rr=(&w26), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #115: @27 = @6[5] */
  for (rr=(&w27), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #116: @27 = (-@27) */
  w27 = (- w27 );
  /* #117: @17 = horzcat(@13, @10, @26, @27) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  /* #118: @17 = @17' */
  /* #119: @13 = @6[7] */
  for (rr=(&w13), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #120: @10 = @6[6] */
  for (rr=(&w10), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #121: @10 = (-@10) */
  w10 = (- w10 );
  /* #122: @26 = @6[5] */
  for (rr=(&w26), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #123: @27 = @6[4] */
  for (rr=(&w27), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #124: @38 = horzcat(@13, @10, @26, @27) */
  rr=w38;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  /* #125: @38 = @38' */
  /* #126: @22 = horzcat(@15, @16, @17, @38) */
  rr=w22;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<4; ++i) *rr++ = *cs++;
  /* #127: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #128: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #129: @13 = @6[0] */
  for (rr=(&w13), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #130: @10 = @6[1] */
  for (rr=(&w10), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #131: @10 = (-@10) */
  w10 = (- w10 );
  /* #132: @26 = @6[2] */
  for (rr=(&w26), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #133: @26 = (-@26) */
  w26 = (- w26 );
  /* #134: @27 = @6[3] */
  for (rr=(&w27), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #135: @27 = (-@27) */
  w27 = (- w27 );
  /* #136: @15 = vertcat(@13, @10, @26, @27) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  /* #137: @12 = mac(@19,@15,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w19+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #138: @13 = @12[1] */
  for (rr=(&w13), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #139: @8 = (@8*@13) */
  w08 *= w13;
  /* #140: @13 = 0.5 */
  w13 = 5.0000000000000000e-01;
  /* #141: @10 = @12[2] */
  for (rr=(&w10), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #142: @13 = (@13*@10) */
  w13 *= w10;
  /* #143: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #144: @26 = @12[3] */
  for (rr=(&w26), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #145: @10 = (@10*@26) */
  w10 *= w26;
  /* #146: @6 = vertcat(@3, @4, @11, @9, @14, @8, @13, @10) */
  rr=w06;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w10;
  /* #147: @36 = @6' */
  casadi_copy(w06, 8, w36);
  /* #148: @25 = zeros(8x8) */
  casadi_clear(w25, 64);
  /* #149: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #150: (@25[0] = @3) */
  for (rr=w25+0, cs=(&w03); rr!=w25+1; rr+=1) *rr = *cs++;
  /* #151: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #152: (@25[9] = @3) */
  for (rr=w25+9, cs=(&w03); rr!=w25+10; rr+=1) *rr = *cs++;
  /* #153: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #154: (@25[18] = @3) */
  for (rr=w25+18, cs=(&w03); rr!=w25+19; rr+=1) *rr = *cs++;
  /* #155: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #156: (@25[27] = @3) */
  for (rr=w25+27, cs=(&w03); rr!=w25+28; rr+=1) *rr = *cs++;
  /* #157: @3 = 2 */
  w03 = 2.;
  /* #158: (@25[36] = @3) */
  for (rr=w25+36, cs=(&w03); rr!=w25+37; rr+=1) *rr = *cs++;
  /* #159: @3 = 2 */
  w03 = 2.;
  /* #160: (@25[45] = @3) */
  for (rr=w25+45, cs=(&w03); rr!=w25+46; rr+=1) *rr = *cs++;
  /* #161: @3 = 2 */
  w03 = 2.;
  /* #162: (@25[54] = @3) */
  for (rr=w25+54, cs=(&w03); rr!=w25+55; rr+=1) *rr = *cs++;
  /* #163: @3 = 2 */
  w03 = 2.;
  /* #164: (@25[63] = @3) */
  for (rr=w25+63, cs=(&w03); rr!=w25+64; rr+=1) *rr = *cs++;
  /* #165: @2 = mac(@36,@25,@2) */
  for (i=0, rr=w02; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w25+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @1 = mac(@2,@6,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=w06+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #167: @0 = (@0*@1) */
  w00 *= w01;
  /* #168: @1 = 0.01 */
  w01 = 1.0000000000000000e-02;
  /* #169: @3 = 0 */
  w03 = 0.;
  /* #170: @39 = zeros(1x7) */
  casadi_clear(w39, 7);
  /* #171: @40 = @7[15:22] */
  wr40 = wr07+15;
  /* #172: @4 = input[1][0] */
  w04 = arg[1] ? arg[1][0] : 0;
  /* #173: @11 = input[1][1] */
  w11 = arg[1] ? arg[1][1] : 0;
  /* #174: @9 = input[1][2] */
  w09 = arg[1] ? arg[1][2] : 0;
  /* #175: @14 = input[1][3] */
  w14 = arg[1] ? arg[1][3] : 0;
  /* #176: @8 = input[1][4] */
  w08 = arg[1] ? arg[1][4] : 0;
  /* #177: @13 = input[1][5] */
  w13 = arg[1] ? arg[1][5] : 0;
  /* #178: @10 = input[1][6] */
  w10 = arg[1] ? arg[1][6] : 0;
  /* #179: @41 = vertcat(@4, @11, @9, @14, @8, @13, @10) */
  rr=w41;
  *rr++ = w04;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w10;
  /* #180: @40 = (@40-@41) */
  for (i=0, rr=w40, cr=wr40, cs=w41; i<7; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #181: @41 = @40' */
  casadi_copy(w40, 7, w41);
  /* #182: @42 = zeros(7x7) */
  casadi_clear(w42, 49);
  /* #183: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #184: (@42[0] = @4) */
  for (rr=w42+0, cs=(&w04); rr!=w42+1; rr+=1) *rr = *cs++;
  /* #185: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #186: (@42[8] = @4) */
  for (rr=w42+8, cs=(&w04); rr!=w42+9; rr+=1) *rr = *cs++;
  /* #187: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #188: (@42[16] = @4) */
  for (rr=w42+16, cs=(&w04); rr!=w42+17; rr+=1) *rr = *cs++;
  /* #189: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #190: (@42[24] = @4) */
  for (rr=w42+24, cs=(&w04); rr!=w42+25; rr+=1) *rr = *cs++;
  /* #191: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #192: (@42[32] = @4) */
  for (rr=w42+32, cs=(&w04); rr!=w42+33; rr+=1) *rr = *cs++;
  /* #193: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #194: (@42[40] = @4) */
  for (rr=w42+40, cs=(&w04); rr!=w42+41; rr+=1) *rr = *cs++;
  /* #195: @4 = 16.6667 */
  w04 = 1.6666666666666668e+01;
  /* #196: (@42[48] = @4) */
  for (rr=w42+48, cs=(&w04); rr!=w42+49; rr+=1) *rr = *cs++;
  /* #197: @39 = mac(@41,@42,@39) */
  for (i=0, rr=w39; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w42+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #198: @3 = mac(@39,@40,@3) */
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w39+j, ct=w40+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #199: @1 = (@1*@3) */
  w01 *= w03;
  /* #200: @0 = (@0+@1) */
  w00 += w01;
  /* #201: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinova_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 456;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 456*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
