/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinova_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {22, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* kinova_cost_ext_cost_e_fun_jac:(i0[15],i1[0],i2[0],i3[22])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+10, w03, *w04=w+19, *w05=w+22, w07, w08, w09, w10, *w11=w+56;
  casadi_real w12, w13, *w14=w+62, *w15=w+66, *w16=w+70, *w17=w+74, *w18=w+90, *w19=w+106, *w20=w+138, *w21=w+170, *w22=w+186, *w23=w+202;
  casadi_real *w24=w+234, *w25=w+298, w26, w27, w28, w29, w30, w31, w32, w33, w34, *w35=w+371;
  casadi_real *w36=w+386, *w37=w+394, *w38=w+402, w39, *w40=w+406, *w41=w+410, *w42=w+418;
  const casadi_real *cs, *ct, *wr06;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w02, 8);
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = all_2.22045e-16(3x1) */
  casadi_fill(w04, 3, 2.2204460492503131e-16);
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w05, 8);
  /* #6: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #7: @7 = @6[0] */
  w07 = wr06[0];
  /* #8: @8 = @6[1] */
  w08 = wr06[1];
  /* #9: @9 = @6[2] */
  w09 = wr06[2];
  /* #10: @10 = @6[3] */
  w10 = wr06[3];
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @12 = (-@8) */
  w12 = (- w08 );
  /* #14: @13 = (-@9) */
  w13 = (- w09 );
  /* #15: @14 = horzcat(@12, @7, @10, @13) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w13;
  /* #16: @14 = @14' */
  /* #17: @10 = (-@10) */
  w10 = (- w10 );
  /* #18: @15 = horzcat(@13, @10, @7, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w08;
  /* #19: @15 = @15' */
  /* #20: @16 = horzcat(@10, @9, @12, @7) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w07;
  /* #21: @16 = @16' */
  /* #22: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #23: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #24: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #25: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #26: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #27: @10 = @6[4] */
  w10 = wr06[4];
  /* #28: @9 = @6[5] */
  w09 = wr06[5];
  /* #29: @12 = @6[6] */
  w12 = wr06[6];
  /* #30: @7 = @6[7] */
  w07 = wr06[7];
  /* #31: @11 = horzcat(@10, @9, @12, @7) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w07;
  /* #32: @11 = @11' */
  /* #33: @13 = (-@9) */
  w13 = (- w09 );
  /* #34: @8 = (-@12) */
  w08 = (- w12 );
  /* #35: @14 = horzcat(@13, @10, @7, @8) */
  rr=w14;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w08;
  /* #36: @14 = @14' */
  /* #37: @7 = (-@7) */
  w07 = (- w07 );
  /* #38: @15 = horzcat(@8, @7, @10, @9) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w09;
  /* #39: @15 = @15' */
  /* #40: @16 = horzcat(@7, @12, @13, @10) */
  rr=w16;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w10;
  /* #41: @16 = @16' */
  /* #42: @21 = horzcat(@11, @14, @15, @16) */
  rr=w21;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #43: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #44: @19 = horzcat(@22, @18) */
  rr=w19;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #45: @23 = @19' */
  for (i=0, rr=w23, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #46: @24 = horzcat(@20, @23) */
  rr=w24;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<32; ++i) *rr++ = *cs++;
  /* #47: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #48: @7 = input[0][0] */
  w07 = arg[0] ? arg[0][0] : 0;
  /* #49: @12 = input[0][1] */
  w12 = arg[0] ? arg[0][1] : 0;
  /* #50: @13 = input[0][2] */
  w13 = arg[0] ? arg[0][2] : 0;
  /* #51: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #52: @8 = input[0][4] */
  w08 = arg[0] ? arg[0][4] : 0;
  /* #53: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #54: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #55: @27 = input[0][7] */
  w27 = arg[0] ? arg[0][7] : 0;
  /* #56: @28 = input[0][8] */
  w28 = arg[0] ? arg[0][8] : 0;
  /* #57: @29 = input[0][9] */
  w29 = arg[0] ? arg[0][9] : 0;
  /* #58: @30 = input[0][10] */
  w30 = arg[0] ? arg[0][10] : 0;
  /* #59: @31 = input[0][11] */
  w31 = arg[0] ? arg[0][11] : 0;
  /* #60: @32 = input[0][12] */
  w32 = arg[0] ? arg[0][12] : 0;
  /* #61: @33 = input[0][13] */
  w33 = arg[0] ? arg[0][13] : 0;
  /* #62: @34 = input[0][14] */
  w34 = arg[0] ? arg[0][14] : 0;
  /* #63: @35 = vertcat(@7, @12, @13, @10, @8, @9, @26, @27, @28, @29, @30, @31, @32, @33, @34) */
  rr=w35;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  /* #64: @36 = @35[:8] */
  for (rr=w36, cs=w35+0; cs!=w35+8; cs+=1) *rr++ = *cs;
  /* #65: @37 = mac(@25,@36,@5) */
  casadi_copy(w05, 8, w37);
  for (i=0, rr=w37; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w25+j, ct=w36+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #66: @38 = @37[1:4] */
  for (rr=w38, cs=w37+1; cs!=w37+4; cs+=1) *rr++ = *cs;
  /* #67: @4 = (@4+@38) */
  for (i=0, rr=w04, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #68: @7 = ||@4||_F */
  w07 = casadi_norm_2(3, w04);
  /* #69: @12 = @37[0] */
  for (rr=(&w12), cs=w37+0; cs!=w37+1; cs+=1) *rr++ = *cs;
  /* #70: @13 = atan2(@7,@12) */
  w13  = atan2(w07,w12);
  /* #71: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #72: @13 = (@3*@13) */
  w13  = (w03*w13);
  /* #73: @10 = @37[1] */
  for (rr=(&w10), cs=w37+1; cs!=w37+2; cs+=1) *rr++ = *cs;
  /* #74: @8 = (@13*@10) */
  w08  = (w13*w10);
  /* #75: @8 = (@8/@7) */
  w08 /= w07;
  /* #76: @9 = @37[2] */
  for (rr=(&w09), cs=w37+2; cs!=w37+3; cs+=1) *rr++ = *cs;
  /* #77: @26 = (@13*@9) */
  w26  = (w13*w09);
  /* #78: @26 = (@26/@7) */
  w26 /= w07;
  /* #79: @27 = @37[3] */
  for (rr=(&w27), cs=w37+3; cs!=w37+4; cs+=1) *rr++ = *cs;
  /* #80: @28 = (@13*@27) */
  w28  = (w13*w27);
  /* #81: @28 = (@28/@7) */
  w28 /= w07;
  /* #82: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #83: @29 = @37[4] */
  for (rr=(&w29), cs=w37+4; cs!=w37+5; cs+=1) *rr++ = *cs;
  /* #84: @30 = @37[5] */
  for (rr=(&w30), cs=w37+5; cs!=w37+6; cs+=1) *rr++ = *cs;
  /* #85: @31 = (-@30) */
  w31 = (- w30 );
  /* #86: @32 = @37[6] */
  for (rr=(&w32), cs=w37+6; cs!=w37+7; cs+=1) *rr++ = *cs;
  /* #87: @33 = (-@32) */
  w33 = (- w32 );
  /* #88: @34 = @37[7] */
  for (rr=(&w34), cs=w37+7; cs!=w37+8; cs+=1) *rr++ = *cs;
  /* #89: @39 = (-@34) */
  w39 = (- w34 );
  /* #90: @14 = horzcat(@29, @31, @33, @39) */
  rr=w14;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w33;
  *rr++ = w39;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@30, @29, @39, @32) */
  rr=w15;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w39;
  *rr++ = w32;
  /* #93: @15 = @15' */
  /* #94: @16 = horzcat(@32, @34, @29, @31) */
  rr=w16;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w29;
  *rr++ = w31;
  /* #95: @16 = @16' */
  /* #96: @40 = horzcat(@34, @33, @30, @29) */
  rr=w40;
  *rr++ = w34;
  *rr++ = w33;
  *rr++ = w30;
  *rr++ = w29;
  /* #97: @40 = @40' */
  /* #98: @22 = horzcat(@14, @15, @16, @40) */
  rr=w22;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<4; ++i) *rr++ = *cs++;
  /* #99: @18 = @22' */
  for (i=0, rr=w18, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #100: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #101: @34 = (-@10) */
  w34 = (- w10 );
  /* #102: @33 = (-@9) */
  w33 = (- w09 );
  /* #103: @30 = (-@27) */
  w30 = (- w27 );
  /* #104: @14 = vertcat(@12, @34, @33, @30) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w34;
  *rr++ = w33;
  *rr++ = w30;
  /* #105: @15 = mac(@18,@14,@11) */
  casadi_copy(w11, 4, w15);
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w18+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #106: @34 = @15[1] */
  for (rr=(&w34), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #107: @34 = (@3*@34) */
  w34  = (w03*w34);
  /* #108: @33 = @15[2] */
  for (rr=(&w33), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #109: @33 = (@3*@33) */
  w33  = (w03*w33);
  /* #110: @30 = @15[3] */
  for (rr=(&w30), cs=w15+3; cs!=w15+4; cs+=1) *rr++ = *cs;
  /* #111: @30 = (@3*@30) */
  w30  = (w03*w30);
  /* #112: @37 = vertcat(@1, @8, @26, @28, @1, @34, @33, @30) */
  rr=w37;
  *rr++ = w01;
  *rr++ = w08;
  *rr++ = w26;
  *rr++ = w28;
  *rr++ = w01;
  *rr++ = w34;
  *rr++ = w33;
  *rr++ = w30;
  /* #113: @36 = @37' */
  casadi_copy(w37, 8, w36);
  /* #114: @25 = zeros(8x8) */
  casadi_clear(w25, 64);
  /* #115: @34 = 0.1 */
  w34 = 1.0000000000000001e-01;
  /* #116: (@25[0] = @34) */
  for (rr=w25+0, cs=(&w34); rr!=w25+1; rr+=1) *rr = *cs++;
  /* #117: (@25[9] = @34) */
  for (rr=w25+9, cs=(&w34); rr!=w25+10; rr+=1) *rr = *cs++;
  /* #118: (@25[18] = @34) */
  for (rr=w25+18, cs=(&w34); rr!=w25+19; rr+=1) *rr = *cs++;
  /* #119: (@25[27] = @34) */
  for (rr=w25+27, cs=(&w34); rr!=w25+28; rr+=1) *rr = *cs++;
  /* #120: @34 = 2 */
  w34 = 2.;
  /* #121: (@25[36] = @34) */
  for (rr=w25+36, cs=(&w34); rr!=w25+37; rr+=1) *rr = *cs++;
  /* #122: (@25[45] = @34) */
  for (rr=w25+45, cs=(&w34); rr!=w25+46; rr+=1) *rr = *cs++;
  /* #123: (@25[54] = @34) */
  for (rr=w25+54, cs=(&w34); rr!=w25+55; rr+=1) *rr = *cs++;
  /* #124: (@25[63] = @34) */
  for (rr=w25+63, cs=(&w34); rr!=w25+64; rr+=1) *rr = *cs++;
  /* #125: @41 = mac(@36,@25,@2) */
  casadi_copy(w02, 8, w41);
  for (i=0, rr=w41; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w25+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #126: @1 = mac(@41,@37,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w41+j, ct=w37+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #127: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #128: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #129: @35 = zeros(15x1) */
  casadi_clear(w35, 15);
  /* #130: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #131: @41 = @41' */
  /* #132: @41 = (@0*@41) */
  for (i=0, rr=w41, cs=w41; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #133: @36 = (@0*@36) */
  for (i=0, rr=w36, cs=w36; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #134: @42 = @25' */
  for (i=0, rr=w42, cs=w25; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #135: @2 = mac(@36,@42,@2) */
  for (i=0, rr=w02; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w42+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #136: @2 = @2' */
  /* #137: @41 = (@41+@2) */
  for (i=0, rr=w41, cs=w02; i<8; ++i) (*rr++) += (*cs++);
  /* #138: {NULL, @0, @1, @34, NULL, @33, @30, @29} = vertsplit(@41) */
  w00 = w41[1];
  w01 = w41[2];
  w34 = w41[3];
  w33 = w41[5];
  w30 = w41[6];
  w29 = w41[7];
  /* #139: @29 = (@3*@29) */
  w29  = (w03*w29);
  /* #140: @15 = @11; (@15[3] += @29) */
  casadi_copy(w11, 4, w15);
  for (rr=w15+3, cs=(&w29); rr!=w15+4; rr+=1) *rr += *cs++;
  /* #141: @30 = (@3*@30) */
  w30  = (w03*w30);
  /* #142: (@15[2] += @30) */
  for (rr=w15+2, cs=(&w30); rr!=w15+3; rr+=1) *rr += *cs++;
  /* #143: @33 = (@3*@33) */
  w33  = (w03*w33);
  /* #144: (@15[1] += @33) */
  for (rr=w15+1, cs=(&w33); rr!=w15+2; rr+=1) *rr += *cs++;
  /* #145: @11 = mac(@22,@15,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w22+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #146: {@33, @30, @29, @32} = vertsplit(@11) */
  w33 = w11[0];
  w30 = w11[1];
  w29 = w11[2];
  w32 = w11[3];
  /* #147: @32 = (-@32) */
  w32 = (- w32 );
  /* #148: @41 = @5; (@41[3] += @32) */
  casadi_copy(w05, 8, w41);
  for (rr=w41+3, cs=(&w32); rr!=w41+4; rr+=1) *rr += *cs++;
  /* #149: @29 = (-@29) */
  w29 = (- w29 );
  /* #150: (@41[2] += @29) */
  for (rr=w41+2, cs=(&w29); rr!=w41+3; rr+=1) *rr += *cs++;
  /* #151: @30 = (-@30) */
  w30 = (- w30 );
  /* #152: (@41[1] += @30) */
  for (rr=w41+1, cs=(&w30); rr!=w41+2; rr+=1) *rr += *cs++;
  /* #153: (@41[0] += @33) */
  for (rr=w41+0, cs=(&w33); rr!=w41+1; rr+=1) *rr += *cs++;
  /* #154: @14 = @14' */
  /* #155: @17 = mac(@15,@14,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w15+j, ct=w14+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #156: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #157: @22 = @17' */
  for (i=0, rr=w22, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #158: {@15, @14, @11, @16} = horzsplit(@22) */
  casadi_copy(w22, 4, w15);
  casadi_copy(w22+4, 4, w14);
  casadi_copy(w22+8, 4, w11);
  casadi_copy(w22+12, 4, w16);
  /* #159: @16 = @16' */
  /* #160: {@33, @30, @29, @32} = horzsplit(@16) */
  w33 = w16[0];
  w30 = w16[1];
  w29 = w16[2];
  w32 = w16[3];
  /* #161: (@41[4] += @32) */
  for (rr=w41+4, cs=(&w32); rr!=w41+5; rr+=1) *rr += *cs++;
  /* #162: (@41[5] += @29) */
  for (rr=w41+5, cs=(&w29); rr!=w41+6; rr+=1) *rr += *cs++;
  /* #163: @30 = (-@30) */
  w30 = (- w30 );
  /* #164: (@41[6] += @30) */
  for (rr=w41+6, cs=(&w30); rr!=w41+7; rr+=1) *rr += *cs++;
  /* #165: (@41[7] += @33) */
  for (rr=w41+7, cs=(&w33); rr!=w41+8; rr+=1) *rr += *cs++;
  /* #166: @11 = @11' */
  /* #167: {@33, @30, @29, @32} = horzsplit(@11) */
  w33 = w11[0];
  w30 = w11[1];
  w29 = w11[2];
  w32 = w11[3];
  /* #168: @32 = (-@32) */
  w32 = (- w32 );
  /* #169: (@41[5] += @32) */
  for (rr=w41+5, cs=(&w32); rr!=w41+6; rr+=1) *rr += *cs++;
  /* #170: (@41[4] += @29) */
  for (rr=w41+4, cs=(&w29); rr!=w41+5; rr+=1) *rr += *cs++;
  /* #171: (@41[7] += @30) */
  for (rr=w41+7, cs=(&w30); rr!=w41+8; rr+=1) *rr += *cs++;
  /* #172: (@41[6] += @33) */
  for (rr=w41+6, cs=(&w33); rr!=w41+7; rr+=1) *rr += *cs++;
  /* #173: @14 = @14' */
  /* #174: {@33, @30, @29, @32} = horzsplit(@14) */
  w33 = w14[0];
  w30 = w14[1];
  w29 = w14[2];
  w32 = w14[3];
  /* #175: (@41[6] += @32) */
  for (rr=w41+6, cs=(&w32); rr!=w41+7; rr+=1) *rr += *cs++;
  /* #176: @29 = (-@29) */
  w29 = (- w29 );
  /* #177: (@41[7] += @29) */
  for (rr=w41+7, cs=(&w29); rr!=w41+8; rr+=1) *rr += *cs++;
  /* #178: (@41[4] += @30) */
  for (rr=w41+4, cs=(&w30); rr!=w41+5; rr+=1) *rr += *cs++;
  /* #179: (@41[5] += @33) */
  for (rr=w41+5, cs=(&w33); rr!=w41+6; rr+=1) *rr += *cs++;
  /* #180: @15 = @15' */
  /* #181: {@33, @30, @29, @32} = horzsplit(@15) */
  w33 = w15[0];
  w30 = w15[1];
  w29 = w15[2];
  w32 = w15[3];
  /* #182: @32 = (-@32) */
  w32 = (- w32 );
  /* #183: (@41[7] += @32) */
  for (rr=w41+7, cs=(&w32); rr!=w41+8; rr+=1) *rr += *cs++;
  /* #184: @29 = (-@29) */
  w29 = (- w29 );
  /* #185: (@41[6] += @29) */
  for (rr=w41+6, cs=(&w29); rr!=w41+7; rr+=1) *rr += *cs++;
  /* #186: @30 = (-@30) */
  w30 = (- w30 );
  /* #187: (@41[5] += @30) */
  for (rr=w41+5, cs=(&w30); rr!=w41+6; rr+=1) *rr += *cs++;
  /* #188: (@41[4] += @33) */
  for (rr=w41+4, cs=(&w33); rr!=w41+5; rr+=1) *rr += *cs++;
  /* #189: @33 = (@34/@7) */
  w33  = (w34/w07);
  /* #190: @30 = (@13*@33) */
  w30  = (w13*w33);
  /* #191: (@41[3] += @30) */
  for (rr=w41+3, cs=(&w30); rr!=w41+4; rr+=1) *rr += *cs++;
  /* #192: @30 = (@1/@7) */
  w30  = (w01/w07);
  /* #193: @29 = (@13*@30) */
  w29  = (w13*w30);
  /* #194: (@41[2] += @29) */
  for (rr=w41+2, cs=(&w29); rr!=w41+3; rr+=1) *rr += *cs++;
  /* #195: @29 = (@0/@7) */
  w29  = (w00/w07);
  /* #196: @13 = (@13*@29) */
  w13 *= w29;
  /* #197: (@41[1] += @13) */
  for (rr=w41+1, cs=(&w13); rr!=w41+2; rr+=1) *rr += *cs++;
  /* #198: @13 = sq(@7) */
  w13 = casadi_sq( w07 );
  /* #199: @32 = sq(@12) */
  w32 = casadi_sq( w12 );
  /* #200: @13 = (@13+@32) */
  w13 += w32;
  /* #201: @32 = (@7/@13) */
  w32  = (w07/w13);
  /* #202: @27 = (@27*@33) */
  w27 *= w33;
  /* #203: @27 = (@3*@27) */
  w27  = (w03*w27);
  /* #204: @9 = (@9*@30) */
  w09 *= w30;
  /* #205: @9 = (@3*@9) */
  w09  = (w03*w09);
  /* #206: @27 = (@27+@9) */
  w27 += w09;
  /* #207: @10 = (@10*@29) */
  w10 *= w29;
  /* #208: @3 = (@3*@10) */
  w03 *= w10;
  /* #209: @27 = (@27+@3) */
  w27 += w03;
  /* #210: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #211: @32 = (@32*@27) */
  w32 *= w27;
  /* #212: @32 = (-@32) */
  w32 = (- w32 );
  /* #213: (@41[0] += @32) */
  for (rr=w41+0, cs=(&w32); rr!=w41+1; rr+=1) *rr += *cs++;
  /* #214: @26 = (@26/@7) */
  w26 /= w07;
  /* #215: @26 = (@26*@1) */
  w26 *= w01;
  /* #216: @26 = (-@26) */
  w26 = (- w26 );
  /* #217: @28 = (@28/@7) */
  w28 /= w07;
  /* #218: @28 = (@28*@34) */
  w28 *= w34;
  /* #219: @26 = (@26-@28) */
  w26 -= w28;
  /* #220: @8 = (@8/@7) */
  w08 /= w07;
  /* #221: @8 = (@8*@0) */
  w08 *= w00;
  /* #222: @26 = (@26-@8) */
  w26 -= w08;
  /* #223: @12 = (@12/@13) */
  w12 /= w13;
  /* #224: @12 = (@12*@27) */
  w12 *= w27;
  /* #225: @26 = (@26+@12) */
  w26 += w12;
  /* #226: @26 = (@26/@7) */
  w26 /= w07;
  /* #227: @4 = (@26*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w26*(*cs++));
  /* #228: (@41[1:4] += @4) */
  for (rr=w41+1, cs=w04; rr!=w41+4; rr+=1) *rr += *cs++;
  /* #229: @5 = mac(@24,@41,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w41+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #230: (@35[:8] += @5) */
  for (rr=w35+0, cs=w05; rr!=w35+8; rr+=1) *rr += *cs++;
  /* #231: output[1][0] = @35 */
  casadi_copy(w35, 15, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real kinova_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 482;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 482*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
