/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinova_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* kinova_cost_ext_cost_fun_jac:(i0[15],i1[7],i2[],i3[22])->(o0,o1[22]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+10, w03, w04, *w05=w+20, *w06=w+23, w08, w09, w10, w11;
  casadi_real *w12=w+57, w13, w14, *w15=w+63, *w16=w+67, *w17=w+71, *w18=w+75, *w19=w+91, *w20=w+107, *w21=w+139, *w22=w+171, *w23=w+187;
  casadi_real *w24=w+219, *w25=w+283, w26, w27, w28, w29, w30, w31, w32, w33, w34, *w35=w+356;
  casadi_real *w36=w+371, *w37=w+379, w38, w39, w40, w41, *w42=w+386, w43, *w44=w+391, *w45=w+398, w46, w47;
  casadi_real w48, *w49=w+408, *w50=w+415, *w51=w+464, *w52=w+513, *w53=w+521, *w54=w+529;
  const casadi_real *cr, *cs, *ct, *wr07, *wr45;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w02, 8);
  /* #3: @3 = 0 */
  w03 = 0.;
  /* #4: @4 = 0.5 */
  w04 = 5.0000000000000000e-01;
  /* #5: @5 = all_2.22045e-16(3x1) */
  casadi_fill(w05, 3, 2.2204460492503131e-16);
  /* #6: @6 = zeros(8x1) */
  casadi_clear(w06, 8);
  /* #7: @7 = input[3][0] */
  wr07 = arg[3] ? arg[3] : casadi_zeros;
  /* #8: @8 = @7[0] */
  w08 = wr07[0];
  /* #9: @9 = @7[1] */
  w09 = wr07[1];
  /* #10: @10 = @7[2] */
  w10 = wr07[2];
  /* #11: @11 = @7[3] */
  w11 = wr07[3];
  /* #12: @12 = horzcat(@8, @9, @10, @11) */
  rr=w12;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  /* #13: @12 = @12' */
  /* #14: @8 = (-@9) */
  w08 = (- w09 );
  /* #15: @13 = @7[0] */
  w13 = wr07[0];
  /* #16: @14 = (-@10) */
  w14 = (- w10 );
  /* #17: @15 = horzcat(@8, @13, @11, @14) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w14;
  /* #18: @15 = @15' */
  /* #19: @11 = (-@11) */
  w11 = (- w11 );
  /* #20: @13 = @7[0] */
  w13 = wr07[0];
  /* #21: @16 = horzcat(@14, @11, @13, @9) */
  rr=w16;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w09;
  /* #22: @16 = @16' */
  /* #23: @14 = @7[0] */
  w14 = wr07[0];
  /* #24: @17 = horzcat(@11, @10, @8, @14) */
  rr=w17;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  /* #25: @17 = @17' */
  /* #26: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #27: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #28: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #29: @20 = horzcat(@19, @18) */
  rr=w20;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #30: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #31: @11 = @7[4] */
  w11 = wr07[4];
  /* #32: @10 = @7[5] */
  w10 = wr07[5];
  /* #33: @8 = @7[6] */
  w08 = wr07[6];
  /* #34: @14 = @7[7] */
  w14 = wr07[7];
  /* #35: @12 = horzcat(@11, @10, @8, @14) */
  rr=w12;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w14;
  /* #36: @12 = @12' */
  /* #37: @11 = (-@10) */
  w11 = (- w10 );
  /* #38: @13 = @7[4] */
  w13 = wr07[4];
  /* #39: @9 = (-@8) */
  w09 = (- w08 );
  /* #40: @15 = horzcat(@11, @13, @14, @9) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w09;
  /* #41: @15 = @15' */
  /* #42: @14 = (-@14) */
  w14 = (- w14 );
  /* #43: @13 = @7[4] */
  w13 = wr07[4];
  /* #44: @16 = horzcat(@9, @14, @13, @10) */
  rr=w16;
  *rr++ = w09;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w10;
  /* #45: @16 = @16' */
  /* #46: @9 = @7[4] */
  w09 = wr07[4];
  /* #47: @17 = horzcat(@14, @8, @11, @9) */
  rr=w17;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w09;
  /* #48: @17 = @17' */
  /* #49: @18 = horzcat(@12, @15, @16, @17) */
  rr=w18;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  /* #50: @22 = @18' */
  for (i=0, rr=w22, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #51: @20 = horzcat(@22, @19) */
  rr=w20;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<16; ++i) *rr++ = *cs++;
  /* #52: @23 = @20' */
  for (i=0, rr=w23, cs=w20; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #53: @24 = horzcat(@21, @23) */
  rr=w24;
  for (i=0, cs=w21; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<32; ++i) *rr++ = *cs++;
  /* #54: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #55: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #56: @8 = input[0][1] */
  w08 = arg[0] ? arg[0][1] : 0;
  /* #57: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #58: @9 = input[0][3] */
  w09 = arg[0] ? arg[0][3] : 0;
  /* #59: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #60: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #61: @26 = input[0][6] */
  w26 = arg[0] ? arg[0][6] : 0;
  /* #62: @27 = input[0][7] */
  w27 = arg[0] ? arg[0][7] : 0;
  /* #63: @28 = input[0][8] */
  w28 = arg[0] ? arg[0][8] : 0;
  /* #64: @29 = input[0][9] */
  w29 = arg[0] ? arg[0][9] : 0;
  /* #65: @30 = input[0][10] */
  w30 = arg[0] ? arg[0][10] : 0;
  /* #66: @31 = input[0][11] */
  w31 = arg[0] ? arg[0][11] : 0;
  /* #67: @32 = input[0][12] */
  w32 = arg[0] ? arg[0][12] : 0;
  /* #68: @33 = input[0][13] */
  w33 = arg[0] ? arg[0][13] : 0;
  /* #69: @34 = input[0][14] */
  w34 = arg[0] ? arg[0][14] : 0;
  /* #70: @35 = vertcat(@14, @8, @11, @9, @13, @10, @26, @27, @28, @29, @30, @31, @32, @33, @34) */
  rr=w35;
  *rr++ = w14;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w34;
  /* #71: @36 = @35[:8] */
  for (rr=w36, cs=w35+0; cs!=w35+8; cs+=1) *rr++ = *cs;
  /* #72: @6 = mac(@25,@36,@6) */
  for (i=0, rr=w06; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w25+j, ct=w36+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #73: @37 = @6[1:4] */
  for (rr=w37, cs=w06+1; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #74: @5 = (@5+@37) */
  for (i=0, rr=w05, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #75: @14 = ||@5||_F */
  w14 = casadi_norm_2(3, w05);
  /* #76: @8 = @6[0] */
  for (rr=(&w08), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #77: @11 = atan2(@14,@8) */
  w11  = atan2(w14,w08);
  /* #78: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #79: @9 = (@4*@11) */
  w09  = (w04*w11);
  /* #80: @13 = @6[1] */
  for (rr=(&w13), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #81: @10 = (@9*@13) */
  w10  = (w09*w13);
  /* #82: @10 = (@10/@14) */
  w10 /= w14;
  /* #83: @26 = 0.5 */
  w26 = 5.0000000000000000e-01;
  /* #84: @27 = (@26*@11) */
  w27  = (w26*w11);
  /* #85: @28 = @6[2] */
  for (rr=(&w28), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #86: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #87: @29 = (@29/@14) */
  w29 /= w14;
  /* #88: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #89: @11 = (@30*@11) */
  w11  = (w30*w11);
  /* #90: @31 = @6[3] */
  for (rr=(&w31), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #91: @32 = (@11*@31) */
  w32  = (w11*w31);
  /* #92: @32 = (@32/@14) */
  w32 /= w14;
  /* #93: @33 = 0 */
  w33 = 0.;
  /* #94: @34 = 0.5 */
  w34 = 5.0000000000000000e-01;
  /* #95: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #96: @38 = @6[4] */
  for (rr=(&w38), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #97: @39 = @6[5] */
  for (rr=(&w39), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #98: @39 = (-@39) */
  w39 = (- w39 );
  /* #99: @40 = @6[6] */
  for (rr=(&w40), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #100: @40 = (-@40) */
  w40 = (- w40 );
  /* #101: @41 = @6[7] */
  for (rr=(&w41), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #102: @41 = (-@41) */
  w41 = (- w41 );
  /* #103: @15 = horzcat(@38, @39, @40, @41) */
  rr=w15;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #104: @15 = @15' */
  /* #105: @38 = @6[5] */
  for (rr=(&w38), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #106: @39 = @6[4] */
  for (rr=(&w39), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #107: @40 = @6[7] */
  for (rr=(&w40), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #108: @40 = (-@40) */
  w40 = (- w40 );
  /* #109: @41 = @6[6] */
  for (rr=(&w41), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #110: @16 = horzcat(@38, @39, @40, @41) */
  rr=w16;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #111: @16 = @16' */
  /* #112: @38 = @6[6] */
  for (rr=(&w38), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #113: @39 = @6[7] */
  for (rr=(&w39), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #114: @40 = @6[4] */
  for (rr=(&w40), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #115: @41 = @6[5] */
  for (rr=(&w41), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #116: @41 = (-@41) */
  w41 = (- w41 );
  /* #117: @17 = horzcat(@38, @39, @40, @41) */
  rr=w17;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #118: @17 = @17' */
  /* #119: @38 = @6[7] */
  for (rr=(&w38), cs=w06+7; cs!=w06+8; cs+=1) *rr++ = *cs;
  /* #120: @39 = @6[6] */
  for (rr=(&w39), cs=w06+6; cs!=w06+7; cs+=1) *rr++ = *cs;
  /* #121: @39 = (-@39) */
  w39 = (- w39 );
  /* #122: @40 = @6[5] */
  for (rr=(&w40), cs=w06+5; cs!=w06+6; cs+=1) *rr++ = *cs;
  /* #123: @41 = @6[4] */
  for (rr=(&w41), cs=w06+4; cs!=w06+5; cs+=1) *rr++ = *cs;
  /* #124: @42 = horzcat(@38, @39, @40, @41) */
  rr=w42;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #125: @42 = @42' */
  /* #126: @22 = horzcat(@15, @16, @17, @42) */
  rr=w22;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<4; ++i) *rr++ = *cs++;
  /* #127: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #128: @19 = (2.*@19) */
  for (i=0, rr=w19, cs=w19; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #129: @38 = @6[0] */
  for (rr=(&w38), cs=w06+0; cs!=w06+1; cs+=1) *rr++ = *cs;
  /* #130: @39 = @6[1] */
  for (rr=(&w39), cs=w06+1; cs!=w06+2; cs+=1) *rr++ = *cs;
  /* #131: @39 = (-@39) */
  w39 = (- w39 );
  /* #132: @40 = @6[2] */
  for (rr=(&w40), cs=w06+2; cs!=w06+3; cs+=1) *rr++ = *cs;
  /* #133: @40 = (-@40) */
  w40 = (- w40 );
  /* #134: @41 = @6[3] */
  for (rr=(&w41), cs=w06+3; cs!=w06+4; cs+=1) *rr++ = *cs;
  /* #135: @41 = (-@41) */
  w41 = (- w41 );
  /* #136: @15 = vertcat(@38, @39, @40, @41) */
  rr=w15;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #137: @12 = mac(@19,@15,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w19+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #138: @38 = @12[1] */
  for (rr=(&w38), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #139: @38 = (@34*@38) */
  w38  = (w34*w38);
  /* #140: @39 = 0.5 */
  w39 = 5.0000000000000000e-01;
  /* #141: @40 = @12[2] */
  for (rr=(&w40), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #142: @40 = (@39*@40) */
  w40  = (w39*w40);
  /* #143: @41 = 0.5 */
  w41 = 5.0000000000000000e-01;
  /* #144: @43 = @12[3] */
  for (rr=(&w43), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #145: @43 = (@41*@43) */
  w43  = (w41*w43);
  /* #146: @6 = vertcat(@3, @10, @29, @32, @33, @38, @40, @43) */
  rr=w06;
  *rr++ = w03;
  *rr++ = w10;
  *rr++ = w29;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w43;
  /* #147: @36 = @6' */
  casadi_copy(w06, 8, w36);
  /* #148: @25 = zeros(8x8) */
  casadi_clear(w25, 64);
  /* #149: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #150: (@25[0] = @3) */
  for (rr=w25+0, cs=(&w03); rr!=w25+1; rr+=1) *rr = *cs++;
  /* #151: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #152: (@25[9] = @3) */
  for (rr=w25+9, cs=(&w03); rr!=w25+10; rr+=1) *rr = *cs++;
  /* #153: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #154: (@25[18] = @3) */
  for (rr=w25+18, cs=(&w03); rr!=w25+19; rr+=1) *rr = *cs++;
  /* #155: @3 = 0.1 */
  w03 = 1.0000000000000001e-01;
  /* #156: (@25[27] = @3) */
  for (rr=w25+27, cs=(&w03); rr!=w25+28; rr+=1) *rr = *cs++;
  /* #157: @3 = 2 */
  w03 = 2.;
  /* #158: (@25[36] = @3) */
  for (rr=w25+36, cs=(&w03); rr!=w25+37; rr+=1) *rr = *cs++;
  /* #159: @3 = 2 */
  w03 = 2.;
  /* #160: (@25[45] = @3) */
  for (rr=w25+45, cs=(&w03); rr!=w25+46; rr+=1) *rr = *cs++;
  /* #161: @3 = 2 */
  w03 = 2.;
  /* #162: (@25[54] = @3) */
  for (rr=w25+54, cs=(&w03); rr!=w25+55; rr+=1) *rr = *cs++;
  /* #163: @3 = 2 */
  w03 = 2.;
  /* #164: (@25[63] = @3) */
  for (rr=w25+63, cs=(&w03); rr!=w25+64; rr+=1) *rr = *cs++;
  /* #165: @2 = mac(@36,@25,@2) */
  for (i=0, rr=w02; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w25+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @1 = mac(@2,@6,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=w06+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #167: @0 = (@0*@1) */
  w00 *= w01;
  /* #168: @1 = 0.01 */
  w01 = 1.0000000000000000e-02;
  /* #169: @3 = 0 */
  w03 = 0.;
  /* #170: @44 = zeros(1x7) */
  casadi_clear(w44, 7);
  /* #171: @45 = @7[15:22] */
  wr45 = wr07+15;
  /* #172: @33 = input[1][0] */
  w33 = arg[1] ? arg[1][0] : 0;
  /* #173: @38 = input[1][1] */
  w38 = arg[1] ? arg[1][1] : 0;
  /* #174: @40 = input[1][2] */
  w40 = arg[1] ? arg[1][2] : 0;
  /* #175: @43 = input[1][3] */
  w43 = arg[1] ? arg[1][3] : 0;
  /* #176: @46 = input[1][4] */
  w46 = arg[1] ? arg[1][4] : 0;
  /* #177: @47 = input[1][5] */
  w47 = arg[1] ? arg[1][5] : 0;
  /* #178: @48 = input[1][6] */
  w48 = arg[1] ? arg[1][6] : 0;
  /* #179: @49 = vertcat(@33, @38, @40, @43, @46, @47, @48) */
  rr=w49;
  *rr++ = w33;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w43;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w48;
  /* #180: @45 = (@45-@49) */
  for (i=0, rr=w45, cr=wr45, cs=w49; i<7; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #181: @49 = @45' */
  casadi_copy(w45, 7, w49);
  /* #182: @50 = zeros(7x7) */
  casadi_clear(w50, 49);
  /* #183: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #184: (@50[0] = @33) */
  for (rr=w50+0, cs=(&w33); rr!=w50+1; rr+=1) *rr = *cs++;
  /* #185: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #186: (@50[8] = @33) */
  for (rr=w50+8, cs=(&w33); rr!=w50+9; rr+=1) *rr = *cs++;
  /* #187: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #188: (@50[16] = @33) */
  for (rr=w50+16, cs=(&w33); rr!=w50+17; rr+=1) *rr = *cs++;
  /* #189: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #190: (@50[24] = @33) */
  for (rr=w50+24, cs=(&w33); rr!=w50+25; rr+=1) *rr = *cs++;
  /* #191: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #192: (@50[32] = @33) */
  for (rr=w50+32, cs=(&w33); rr!=w50+33; rr+=1) *rr = *cs++;
  /* #193: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #194: (@50[40] = @33) */
  for (rr=w50+40, cs=(&w33); rr!=w50+41; rr+=1) *rr = *cs++;
  /* #195: @33 = 16.6667 */
  w33 = 1.6666666666666668e+01;
  /* #196: (@50[48] = @33) */
  for (rr=w50+48, cs=(&w33); rr!=w50+49; rr+=1) *rr = *cs++;
  /* #197: @44 = mac(@49,@50,@44) */
  for (i=0, rr=w44; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=w50+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #198: @3 = mac(@44,@45,@3) */
  for (i=0, rr=(&w03); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w44+j, ct=w45+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #199: @1 = (@1*@3) */
  w01 *= w03;
  /* #200: @0 = (@0+@1) */
  w00 += w01;
  /* #201: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #202: @0 = 0.01 */
  w00 = 1.0000000000000000e-02;
  /* #203: @44 = @44' */
  /* #204: @44 = (@0*@44) */
  for (i=0, rr=w44, cs=w44; i<7; ++i) (*rr++)  = (w00*(*cs++));
  /* #205: @49 = zeros(1x7) */
  casadi_clear(w49, 7);
  /* #206: @45 = @45' */
  /* #207: @45 = (@0*@45) */
  for (i=0, rr=w45, cs=w45; i<7; ++i) (*rr++)  = (w00*(*cs++));
  /* #208: @51 = @50' */
  for (i=0, rr=w51, cs=w50; i<7; ++i) for (j=0; j<7; ++j) rr[i+j*7] = *cs++;
  /* #209: @49 = mac(@45,@51,@49) */
  for (i=0, rr=w49; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w51+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #210: @49 = @49' */
  /* #211: @44 = (@44+@49) */
  for (i=0, rr=w44, cs=w49; i<7; ++i) (*rr++) += (*cs++);
  /* #212: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<7; ++i) *rr++ = (- *cs++ );
  /* #213: {@0, @1, @3, @33, @38, @40, @43} = vertsplit(@44) */
  w00 = w44[0];
  w01 = w44[1];
  w03 = w44[2];
  w33 = w44[3];
  w38 = w44[4];
  w40 = w44[5];
  w43 = w44[6];
  /* #214: output[1][0] = @0 */
  if (res[1]) res[1][0] = w00;
  /* #215: output[1][1] = @1 */
  if (res[1]) res[1][1] = w01;
  /* #216: output[1][2] = @3 */
  if (res[1]) res[1][2] = w03;
  /* #217: output[1][3] = @33 */
  if (res[1]) res[1][3] = w33;
  /* #218: output[1][4] = @38 */
  if (res[1]) res[1][4] = w38;
  /* #219: output[1][5] = @40 */
  if (res[1]) res[1][5] = w40;
  /* #220: output[1][6] = @43 */
  if (res[1]) res[1][6] = w43;
  /* #221: @35 = zeros(15x1) */
  casadi_clear(w35, 15);
  /* #222: @36 = zeros(8x1) */
  casadi_clear(w36, 8);
  /* #223: @52 = zeros(8x1) */
  casadi_clear(w52, 8);
  /* #224: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #225: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #226: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #227: @43 = 10 */
  w43 = 10.;
  /* #228: @2 = @2' */
  /* #229: @2 = (@43*@2) */
  for (i=0, rr=w02, cs=w02; i<8; ++i) (*rr++)  = (w43*(*cs++));
  /* #230: @53 = zeros(1x8) */
  casadi_clear(w53, 8);
  /* #231: @6 = @6' */
  /* #232: @6 = (@43*@6) */
  for (i=0, rr=w06, cs=w06; i<8; ++i) (*rr++)  = (w43*(*cs++));
  /* #233: @54 = @25' */
  for (i=0, rr=w54, cs=w25; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #234: @53 = mac(@6,@54,@53) */
  for (i=0, rr=w53; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w54+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #235: @53 = @53' */
  /* #236: @2 = (@2+@53) */
  for (i=0, rr=w02, cs=w53; i<8; ++i) (*rr++) += (*cs++);
  /* #237: {NULL, @43, @40, @38, NULL, @33, @3, @1} = vertsplit(@2) */
  w43 = w02[1];
  w40 = w02[2];
  w38 = w02[3];
  w33 = w02[5];
  w03 = w02[6];
  w01 = w02[7];
  /* #238: @41 = (@41*@1) */
  w41 *= w01;
  /* #239: (@16[3] += @41) */
  for (rr=w16+3, cs=(&w41); rr!=w16+4; rr+=1) *rr += *cs++;
  /* #240: @39 = (@39*@3) */
  w39 *= w03;
  /* #241: (@16[2] += @39) */
  for (rr=w16+2, cs=(&w39); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #242: @34 = (@34*@33) */
  w34 *= w33;
  /* #243: (@16[1] += @34) */
  for (rr=w16+1, cs=(&w34); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #244: @12 = mac(@22,@16,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w22+j, ct=w16+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #245: {@34, @33, @39, @3} = vertsplit(@12) */
  w34 = w12[0];
  w33 = w12[1];
  w39 = w12[2];
  w03 = w12[3];
  /* #246: @3 = (-@3) */
  w03 = (- w03 );
  /* #247: (@52[3] += @3) */
  for (rr=w52+3, cs=(&w03); rr!=w52+4; rr+=1) *rr += *cs++;
  /* #248: @39 = (-@39) */
  w39 = (- w39 );
  /* #249: (@52[2] += @39) */
  for (rr=w52+2, cs=(&w39); rr!=w52+3; rr+=1) *rr += *cs++;
  /* #250: @33 = (-@33) */
  w33 = (- w33 );
  /* #251: (@52[1] += @33) */
  for (rr=w52+1, cs=(&w33); rr!=w52+2; rr+=1) *rr += *cs++;
  /* #252: (@52[0] += @34) */
  for (rr=w52+0, cs=(&w34); rr!=w52+1; rr+=1) *rr += *cs++;
  /* #253: @22 = zeros(4x4) */
  casadi_clear(w22, 16);
  /* #254: @15 = @15' */
  /* #255: @22 = mac(@16,@15,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w16+j, ct=w15+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #256: @22 = (2.*@22) */
  for (i=0, rr=w22, cs=w22; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #257: @19 = @22' */
  for (i=0, rr=w19, cs=w22; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #258: {@16, @15, @12, @17} = horzsplit(@19) */
  casadi_copy(w19, 4, w16);
  casadi_copy(w19+4, 4, w15);
  casadi_copy(w19+8, 4, w12);
  casadi_copy(w19+12, 4, w17);
  /* #259: @17 = @17' */
  /* #260: {@34, @33, @39, @3} = horzsplit(@17) */
  w34 = w17[0];
  w33 = w17[1];
  w39 = w17[2];
  w03 = w17[3];
  /* #261: (@52[4] += @3) */
  for (rr=w52+4, cs=(&w03); rr!=w52+5; rr+=1) *rr += *cs++;
  /* #262: (@52[5] += @39) */
  for (rr=w52+5, cs=(&w39); rr!=w52+6; rr+=1) *rr += *cs++;
  /* #263: @33 = (-@33) */
  w33 = (- w33 );
  /* #264: (@52[6] += @33) */
  for (rr=w52+6, cs=(&w33); rr!=w52+7; rr+=1) *rr += *cs++;
  /* #265: (@52[7] += @34) */
  for (rr=w52+7, cs=(&w34); rr!=w52+8; rr+=1) *rr += *cs++;
  /* #266: @12 = @12' */
  /* #267: {@34, @33, @39, @3} = horzsplit(@12) */
  w34 = w12[0];
  w33 = w12[1];
  w39 = w12[2];
  w03 = w12[3];
  /* #268: @3 = (-@3) */
  w03 = (- w03 );
  /* #269: (@52[5] += @3) */
  for (rr=w52+5, cs=(&w03); rr!=w52+6; rr+=1) *rr += *cs++;
  /* #270: (@52[4] += @39) */
  for (rr=w52+4, cs=(&w39); rr!=w52+5; rr+=1) *rr += *cs++;
  /* #271: (@52[7] += @33) */
  for (rr=w52+7, cs=(&w33); rr!=w52+8; rr+=1) *rr += *cs++;
  /* #272: (@52[6] += @34) */
  for (rr=w52+6, cs=(&w34); rr!=w52+7; rr+=1) *rr += *cs++;
  /* #273: @15 = @15' */
  /* #274: {@34, @33, @39, @3} = horzsplit(@15) */
  w34 = w15[0];
  w33 = w15[1];
  w39 = w15[2];
  w03 = w15[3];
  /* #275: (@52[6] += @3) */
  for (rr=w52+6, cs=(&w03); rr!=w52+7; rr+=1) *rr += *cs++;
  /* #276: @39 = (-@39) */
  w39 = (- w39 );
  /* #277: (@52[7] += @39) */
  for (rr=w52+7, cs=(&w39); rr!=w52+8; rr+=1) *rr += *cs++;
  /* #278: (@52[4] += @33) */
  for (rr=w52+4, cs=(&w33); rr!=w52+5; rr+=1) *rr += *cs++;
  /* #279: (@52[5] += @34) */
  for (rr=w52+5, cs=(&w34); rr!=w52+6; rr+=1) *rr += *cs++;
  /* #280: @16 = @16' */
  /* #281: {@34, @33, @39, @3} = horzsplit(@16) */
  w34 = w16[0];
  w33 = w16[1];
  w39 = w16[2];
  w03 = w16[3];
  /* #282: @3 = (-@3) */
  w03 = (- w03 );
  /* #283: (@52[7] += @3) */
  for (rr=w52+7, cs=(&w03); rr!=w52+8; rr+=1) *rr += *cs++;
  /* #284: @39 = (-@39) */
  w39 = (- w39 );
  /* #285: (@52[6] += @39) */
  for (rr=w52+6, cs=(&w39); rr!=w52+7; rr+=1) *rr += *cs++;
  /* #286: @33 = (-@33) */
  w33 = (- w33 );
  /* #287: (@52[5] += @33) */
  for (rr=w52+5, cs=(&w33); rr!=w52+6; rr+=1) *rr += *cs++;
  /* #288: (@52[4] += @34) */
  for (rr=w52+4, cs=(&w34); rr!=w52+5; rr+=1) *rr += *cs++;
  /* #289: @34 = (@38/@14) */
  w34  = (w38/w14);
  /* #290: @11 = (@11*@34) */
  w11 *= w34;
  /* #291: (@52[3] += @11) */
  for (rr=w52+3, cs=(&w11); rr!=w52+4; rr+=1) *rr += *cs++;
  /* #292: @11 = (@40/@14) */
  w11  = (w40/w14);
  /* #293: @27 = (@27*@11) */
  w27 *= w11;
  /* #294: (@52[2] += @27) */
  for (rr=w52+2, cs=(&w27); rr!=w52+3; rr+=1) *rr += *cs++;
  /* #295: @27 = (@43/@14) */
  w27  = (w43/w14);
  /* #296: @9 = (@9*@27) */
  w09 *= w27;
  /* #297: (@52[1] += @9) */
  for (rr=w52+1, cs=(&w09); rr!=w52+2; rr+=1) *rr += *cs++;
  /* #298: @9 = sq(@14) */
  w09 = casadi_sq( w14 );
  /* #299: @33 = sq(@8) */
  w33 = casadi_sq( w08 );
  /* #300: @9 = (@9+@33) */
  w09 += w33;
  /* #301: @33 = (@14/@9) */
  w33  = (w14/w09);
  /* #302: @31 = (@31*@34) */
  w31 *= w34;
  /* #303: @30 = (@30*@31) */
  w30 *= w31;
  /* #304: @28 = (@28*@11) */
  w28 *= w11;
  /* #305: @26 = (@26*@28) */
  w26 *= w28;
  /* #306: @30 = (@30+@26) */
  w30 += w26;
  /* #307: @13 = (@13*@27) */
  w13 *= w27;
  /* #308: @4 = (@4*@13) */
  w04 *= w13;
  /* #309: @30 = (@30+@4) */
  w30 += w04;
  /* #310: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #311: @33 = (@33*@30) */
  w33 *= w30;
  /* #312: @33 = (-@33) */
  w33 = (- w33 );
  /* #313: (@52[0] += @33) */
  for (rr=w52+0, cs=(&w33); rr!=w52+1; rr+=1) *rr += *cs++;
  /* #314: @29 = (@29/@14) */
  w29 /= w14;
  /* #315: @29 = (@29*@40) */
  w29 *= w40;
  /* #316: @29 = (-@29) */
  w29 = (- w29 );
  /* #317: @32 = (@32/@14) */
  w32 /= w14;
  /* #318: @32 = (@32*@38) */
  w32 *= w38;
  /* #319: @29 = (@29-@32) */
  w29 -= w32;
  /* #320: @10 = (@10/@14) */
  w10 /= w14;
  /* #321: @10 = (@10*@43) */
  w10 *= w43;
  /* #322: @29 = (@29-@10) */
  w29 -= w10;
  /* #323: @8 = (@8/@9) */
  w08 /= w09;
  /* #324: @8 = (@8*@30) */
  w08 *= w30;
  /* #325: @29 = (@29+@8) */
  w29 += w08;
  /* #326: @29 = (@29/@14) */
  w29 /= w14;
  /* #327: @5 = (@29*@5) */
  for (i=0, rr=w05, cs=w05; i<3; ++i) (*rr++)  = (w29*(*cs++));
  /* #328: (@52[1:4] += @5) */
  for (rr=w52+1, cs=w05; rr!=w52+4; rr+=1) *rr += *cs++;
  /* #329: @36 = mac(@24,@52,@36) */
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w52+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #330: (@35[:8] += @36) */
  for (rr=w35+0, cs=w36; rr!=w35+8; rr+=1) *rr += *cs++;
  /* #331: {@29, @14, @8, @30, @9, @10, @43, @32, @38, @40, @33, @4, @13, @27, @26} = vertsplit(@35) */
  w29 = w35[0];
  w14 = w35[1];
  w08 = w35[2];
  w30 = w35[3];
  w09 = w35[4];
  w10 = w35[5];
  w43 = w35[6];
  w32 = w35[7];
  w38 = w35[8];
  w40 = w35[9];
  w33 = w35[10];
  w04 = w35[11];
  w13 = w35[12];
  w27 = w35[13];
  w26 = w35[14];
  /* #332: output[1][7] = @29 */
  if (res[1]) res[1][7] = w29;
  /* #333: output[1][8] = @14 */
  if (res[1]) res[1][8] = w14;
  /* #334: output[1][9] = @8 */
  if (res[1]) res[1][9] = w08;
  /* #335: output[1][10] = @30 */
  if (res[1]) res[1][10] = w30;
  /* #336: output[1][11] = @9 */
  if (res[1]) res[1][11] = w09;
  /* #337: output[1][12] = @10 */
  if (res[1]) res[1][12] = w10;
  /* #338: output[1][13] = @43 */
  if (res[1]) res[1][13] = w43;
  /* #339: output[1][14] = @32 */
  if (res[1]) res[1][14] = w32;
  /* #340: output[1][15] = @38 */
  if (res[1]) res[1][15] = w38;
  /* #341: output[1][16] = @40 */
  if (res[1]) res[1][16] = w40;
  /* #342: output[1][17] = @33 */
  if (res[1]) res[1][17] = w33;
  /* #343: output[1][18] = @4 */
  if (res[1]) res[1][18] = w04;
  /* #344: output[1][19] = @13 */
  if (res[1]) res[1][19] = w13;
  /* #345: output[1][20] = @27 */
  if (res[1]) res[1][20] = w27;
  /* #346: output[1][21] = @26 */
  if (res[1]) res[1][21] = w26;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real kinova_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 593;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 593*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
