/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinova_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {7, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[22] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* kinova_cost_ext_cost_fun:(i0[15],i1[7],i2[0],i3[22])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+10, w03, *w04=w+19, *w05=w+22, w07, w08, w09, w10, *w11=w+56;
  casadi_real w12, w13, *w14=w+62, *w15=w+66, *w16=w+70, *w17=w+74, *w18=w+90, *w19=w+106, *w20=w+138, *w21=w+170, *w22=w+186, *w23=w+218;
  casadi_real *w24=w+282, w25, w26, w27, w28, w29, w30, w31, w32, w33, *w34=w+355, *w35=w+370;
  casadi_real *w36=w+378, *w37=w+381, *w38=w+385, *w39=w+392, *w40=w+399, *w41=w+406;
  const casadi_real *cr, *cs, *ct, *wr06, *wr39;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x8) */
  casadi_clear(w02, 8);
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = all_2.22045e-16(3x1) */
  casadi_fill(w04, 3, 2.2204460492503131e-16);
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w05, 8);
  /* #6: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #7: @7 = @6[0] */
  w07 = wr06[0];
  /* #8: @8 = @6[1] */
  w08 = wr06[1];
  /* #9: @9 = @6[2] */
  w09 = wr06[2];
  /* #10: @10 = @6[3] */
  w10 = wr06[3];
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @12 = (-@8) */
  w12 = (- w08 );
  /* #14: @13 = (-@9) */
  w13 = (- w09 );
  /* #15: @14 = horzcat(@12, @7, @10, @13) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w13;
  /* #16: @14 = @14' */
  /* #17: @10 = (-@10) */
  w10 = (- w10 );
  /* #18: @15 = horzcat(@13, @10, @7, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w08;
  /* #19: @15 = @15' */
  /* #20: @16 = horzcat(@10, @9, @12, @7) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w07;
  /* #21: @16 = @16' */
  /* #22: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #23: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #24: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #25: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #26: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #27: @10 = @6[4] */
  w10 = wr06[4];
  /* #28: @9 = @6[5] */
  w09 = wr06[5];
  /* #29: @12 = @6[6] */
  w12 = wr06[6];
  /* #30: @7 = @6[7] */
  w07 = wr06[7];
  /* #31: @11 = horzcat(@10, @9, @12, @7) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w07;
  /* #32: @11 = @11' */
  /* #33: @13 = (-@9) */
  w13 = (- w09 );
  /* #34: @8 = (-@12) */
  w08 = (- w12 );
  /* #35: @14 = horzcat(@13, @10, @7, @8) */
  rr=w14;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w08;
  /* #36: @14 = @14' */
  /* #37: @7 = (-@7) */
  w07 = (- w07 );
  /* #38: @15 = horzcat(@8, @7, @10, @9) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w09;
  /* #39: @15 = @15' */
  /* #40: @16 = horzcat(@7, @12, @13, @10) */
  rr=w16;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w10;
  /* #41: @16 = @16' */
  /* #42: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #43: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #44: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #45: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #46: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #47: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #48: @7 = input[0][0] */
  w07 = arg[0] ? arg[0][0] : 0;
  /* #49: @12 = input[0][1] */
  w12 = arg[0] ? arg[0][1] : 0;
  /* #50: @13 = input[0][2] */
  w13 = arg[0] ? arg[0][2] : 0;
  /* #51: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #52: @8 = input[0][4] */
  w08 = arg[0] ? arg[0][4] : 0;
  /* #53: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #54: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #55: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #56: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #57: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #58: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #59: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #60: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #61: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #62: @33 = input[0][14] */
  w33 = arg[0] ? arg[0][14] : 0;
  /* #63: @34 = vertcat(@7, @12, @13, @10, @8, @9, @25, @26, @27, @28, @29, @30, @31, @32, @33) */
  rr=w34;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #64: @35 = @34[:8] */
  for (rr=w35, cs=w34+0; cs!=w34+8; cs+=1) *rr++ = *cs;
  /* #65: @5 = mac(@24,@35,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w35+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #66: @36 = @5[1:4] */
  for (rr=w36, cs=w05+1; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #67: @4 = (@4+@36) */
  for (i=0, rr=w04, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #68: @7 = ||@4||_F */
  w07 = casadi_norm_2(3, w04);
  /* #69: @12 = @5[0] */
  for (rr=(&w12), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #70: @13 = atan2(@7,@12) */
  w13  = atan2(w07,w12);
  /* #71: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #72: @13 = (@3*@13) */
  w13  = (w03*w13);
  /* #73: @10 = @5[1] */
  for (rr=(&w10), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #74: @8 = (@13*@10) */
  w08  = (w13*w10);
  /* #75: @8 = (@8/@7) */
  w08 /= w07;
  /* #76: @9 = @5[2] */
  for (rr=(&w09), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #77: @25 = (@13*@9) */
  w25  = (w13*w09);
  /* #78: @25 = (@25/@7) */
  w25 /= w07;
  /* #79: @26 = @5[3] */
  for (rr=(&w26), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #80: @13 = (@13*@26) */
  w13 *= w26;
  /* #81: @13 = (@13/@7) */
  w13 /= w07;
  /* #82: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #83: @7 = @5[4] */
  for (rr=(&w07), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #84: @27 = @5[5] */
  for (rr=(&w27), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #85: @28 = (-@27) */
  w28 = (- w27 );
  /* #86: @29 = @5[6] */
  for (rr=(&w29), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #87: @30 = (-@29) */
  w30 = (- w29 );
  /* #88: @31 = @5[7] */
  for (rr=(&w31), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #89: @32 = (-@31) */
  w32 = (- w31 );
  /* #90: @14 = horzcat(@7, @28, @30, @32) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w28;
  *rr++ = w30;
  *rr++ = w32;
  /* #91: @14 = @14' */
  /* #92: @15 = horzcat(@27, @7, @32, @29) */
  rr=w15;
  *rr++ = w27;
  *rr++ = w07;
  *rr++ = w32;
  *rr++ = w29;
  /* #93: @15 = @15' */
  /* #94: @16 = horzcat(@29, @31, @7, @28) */
  rr=w16;
  *rr++ = w29;
  *rr++ = w31;
  *rr++ = w07;
  *rr++ = w28;
  /* #95: @16 = @16' */
  /* #96: @37 = horzcat(@31, @30, @27, @7) */
  rr=w37;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w27;
  *rr++ = w07;
  /* #97: @37 = @37' */
  /* #98: @21 = horzcat(@14, @15, @16, @37) */
  rr=w21;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<4; ++i) *rr++ = *cs++;
  /* #99: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #100: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #101: @10 = (-@10) */
  w10 = (- w10 );
  /* #102: @9 = (-@9) */
  w09 = (- w09 );
  /* #103: @26 = (-@26) */
  w26 = (- w26 );
  /* #104: @14 = vertcat(@12, @10, @9, @26) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w26;
  /* #105: @11 = mac(@18,@14,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w18+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #106: @12 = @11[1] */
  for (rr=(&w12), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #107: @12 = (@3*@12) */
  w12  = (w03*w12);
  /* #108: @10 = @11[2] */
  for (rr=(&w10), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #109: @10 = (@3*@10) */
  w10  = (w03*w10);
  /* #110: @9 = @11[3] */
  for (rr=(&w09), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #111: @3 = (@3*@9) */
  w03 *= w09;
  /* #112: @5 = vertcat(@1, @8, @25, @13, @1, @12, @10, @3) */
  rr=w05;
  *rr++ = w01;
  *rr++ = w08;
  *rr++ = w25;
  *rr++ = w13;
  *rr++ = w01;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w03;
  /* #113: @35 = @5' */
  casadi_copy(w05, 8, w35);
  /* #114: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #115: @8 = 0.1 */
  w08 = 1.0000000000000001e-01;
  /* #116: (@24[0] = @8) */
  for (rr=w24+0, cs=(&w08); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #117: (@24[9] = @8) */
  for (rr=w24+9, cs=(&w08); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #118: (@24[18] = @8) */
  for (rr=w24+18, cs=(&w08); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #119: (@24[27] = @8) */
  for (rr=w24+27, cs=(&w08); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #120: @8 = 2 */
  w08 = 2.;
  /* #121: (@24[36] = @8) */
  for (rr=w24+36, cs=(&w08); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #122: (@24[45] = @8) */
  for (rr=w24+45, cs=(&w08); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #123: (@24[54] = @8) */
  for (rr=w24+54, cs=(&w08); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #124: (@24[63] = @8) */
  for (rr=w24+63, cs=(&w08); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #125: @2 = mac(@35,@24,@2) */
  for (i=0, rr=w02; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #126: @8 = mac(@2,@5,@1) */
  casadi_copy((&w01), 1, (&w08));
  for (i=0, rr=(&w08); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=w05+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #127: @0 = (@0*@8) */
  w00 *= w08;
  /* #128: @8 = 0.01 */
  w08 = 1.0000000000000000e-02;
  /* #129: @38 = zeros(1x7) */
  casadi_clear(w38, 7);
  /* #130: @39 = @6[15:22] */
  wr39 = wr06+15;
  /* #131: @25 = input[1][0] */
  w25 = arg[1] ? arg[1][0] : 0;
  /* #132: @13 = input[1][1] */
  w13 = arg[1] ? arg[1][1] : 0;
  /* #133: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #134: @10 = input[1][3] */
  w10 = arg[1] ? arg[1][3] : 0;
  /* #135: @3 = input[1][4] */
  w03 = arg[1] ? arg[1][4] : 0;
  /* #136: @9 = input[1][5] */
  w09 = arg[1] ? arg[1][5] : 0;
  /* #137: @26 = input[1][6] */
  w26 = arg[1] ? arg[1][6] : 0;
  /* #138: @40 = vertcat(@25, @13, @12, @10, @3, @9, @26) */
  rr=w40;
  *rr++ = w25;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w03;
  *rr++ = w09;
  *rr++ = w26;
  /* #139: @39 = (@39-@40) */
  for (i=0, rr=w39, cr=wr39, cs=w40; i<7; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #140: @40 = @39' */
  casadi_copy(w39, 7, w40);
  /* #141: @41 = zeros(7x7) */
  casadi_clear(w41, 49);
  /* #142: @25 = 16.6667 */
  w25 = 1.6666666666666668e+01;
  /* #143: (@41[0] = @25) */
  for (rr=w41+0, cs=(&w25); rr!=w41+1; rr+=1) *rr = *cs++;
  /* #144: (@41[8] = @25) */
  for (rr=w41+8, cs=(&w25); rr!=w41+9; rr+=1) *rr = *cs++;
  /* #145: (@41[16] = @25) */
  for (rr=w41+16, cs=(&w25); rr!=w41+17; rr+=1) *rr = *cs++;
  /* #146: (@41[24] = @25) */
  for (rr=w41+24, cs=(&w25); rr!=w41+25; rr+=1) *rr = *cs++;
  /* #147: (@41[32] = @25) */
  for (rr=w41+32, cs=(&w25); rr!=w41+33; rr+=1) *rr = *cs++;
  /* #148: (@41[40] = @25) */
  for (rr=w41+40, cs=(&w25); rr!=w41+41; rr+=1) *rr = *cs++;
  /* #149: (@41[48] = @25) */
  for (rr=w41+48, cs=(&w25); rr!=w41+49; rr+=1) *rr = *cs++;
  /* #150: @38 = mac(@40,@41,@38) */
  for (i=0, rr=w38; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w40+j, ct=w41+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #151: @1 = mac(@38,@39,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w38+j, ct=w39+i*7; k<7; ++k) *rr += cs[k*1]**ct++;
  /* #152: @8 = (@8*@1) */
  w08 *= w01;
  /* #153: @0 = (@0+@8) */
  w00 += w08;
  /* #154: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinova_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinova_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinova_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinova_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinova_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 455;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinova_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 455*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
